### ISSUE TITLE
vcov.merMod : calc.vcov.hess: no visible global function definition for 'forceSymmetric'

### ISSUE THREAD

**Issue by wviechtb** [lme4/lme4#277]
In the `metafor` package, I make use of `lme4` for fitting certain models. Ideally, I would like to use `requireNamespace("lme4")` as needed (to avoid altering the search path for the rest of the session). I am running into problems when using `vcov()` on a `merMod` object. As far as I can tell, the issue is this:

Inside `vcov.merMod()`, the function `calc.vcov.hess()` is defined, which in turn calls `forceSymmetric()` from the `Matrix` package. This works fine when `Matrix` is listed under `Depends` (as in `lme`). But when using `requireNamespace("lme4")` (without `Matrix` attached, but imported) this leads to: `error in evaluating the argument 'x' in selecting a method for in calc.vcov.hess(h) : could not find function "forceSymmetric"`. Note that the CRAN checks (http://cran.r-project.org/web/checks/check_results_lme4.html) also include the note: `vcov.merMod : calc.vcov.hess: no visible global function definition for 'forceSymmetric'` which seems to be the same issue.

Isn't a simple solution to just replace all calls to `forceSymmetric()` with `Matrix::forceSymmetric()`? I believe that should get rid of that note and solve the problem I am running into.

**Comment by bbolker** [comment]
Huh, this continues to expose my ignorance of R namespaces/importing.  I don't know the most-correct way to solve this; somehow using an explicit `::` feels like a failure (and feels likely to provoke more NOTEs), and Depending on Matrix feels harmless (since it's a recommended package).  I don't have any objection to doing it either way. Thoughts or opinions, @mmaechler ?

**Comment by wviechtb** [comment]
To be honest, my understanding of the namespaces/depends/import stuff is vague at best. But I have been running into this issue quite a bit lately, since CRAN checks are increasingly looking for such things. Here is a related post: http://r.789695.n4.nabble.com/Using-requireNamespace-instead-of-require-td4697570.html This was about a different package, but the underlying issue is the same, as far as I can tell. The solution suggested there was to use `::`.

Putting `Matrix` under `Depends` does solve the issue for me at the moment. But I think using `::` would be fine, makes things more flexible, and should also get rid of that note under the CRAN checks for `lme4`.

But I am happy to learn more from the people that really understand this stuff.

**Comment by mmaechler** [comment]
@wviechtb:   Your suggestion of using  `Matrix::forceSymmetric()` does not make sense to me, as `lme4` already explicitly imports `forceSymmetric()`... ah, now I see: The CRAN check you mention is from an lme4 version of last July.  The github version has long been changed since.

The related post you mention (I corrected to *not* use Nabble !)  is really a different. The recommendation is to **either** import the function **or** use `::`.  

Depending on `Matrix` is I think still pretty crucial: `lme4` provides objects with sparse and other matrices, and if Matrix is not in the search path, many things will not work correctly for such matrices.  Yes, in an ideal R world,  loading the Matrix namespace would be sufficient to also find all class and method definitions that Matrix provides. AFAIK, we (the R developers) are not there yet. 
So, as long as `lme4` needs a `Depends: Matrix` you either need a `Depends: lme4` (easiest, sensible) or your own `Depends: Matrix` (which looks a bit "funny").

**Comment by wviechtb** [comment]
@mmaechler: First of all, sorry about the Nabble link -- I should have linked to the proper archives. And thanks for the clarification! Makes sense. For now, I will actually go with `Depends: Matrix` as I make use of functionality from that package in multiple places (used to have it under `Imports`), but `lme4` is needed for fitting particular kinds of models that some users may never need or come across (and hence my attempt to use `requireNamespace("lme4")` on an as-needed basis).

**Comment by bbolker** [comment]
From the discussion above it sounds like this is already resolved in the development verison.
