### ISSUE TITLE
REMLcrit not found, sometimes, on MacOS

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#302]
From Lu Xiao, via Simon Wood:

The following code

```
require(lme4) 
set.seed(0) 
y <- rnorm(20)
x <- rnorm(20) 
g <-factor(rep(1:2,10)) 
REMLcrit(lmer(y~(1|g)+x)) 
```
has been reported to fail with "could not find function REMLcrit" on:
```
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)
locale:
 [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats graphics grDevices utils datasets methods base 
other attached packages:
[1] gamm4_0.2-3 mgcv_1.8-4  nlme_3.1-120 lme4_1.1-7 Rcpp_0.11.5 Matrix_1.1-5
loaded via a namespace (and not attached):
[1] grid_3.1.3 lattice_0.20-30 MASS_7.3-39 minqa_1.2.4
[5] RcppEigen_0.3.2.4.0 splines_3.1.3 tools_3.1.3
```
this also causes a problem within `gamm4`, as reflected by the [CRAN check results](http://cran.r-project.org/web/checks/check_results_gamm4.html) for [Snow Leopard](http://www.r-project.org/nosvn/R.check/r-release-osx-x86_64-snowleopard/gamm4-00check.html).

I failed to reproduce, as did Steve Walker (he points out that Luo is running Yosemite (10.10) and neither of us is (I'm at 10.9.5). On the other hand, the CRAN failure is for Snow Leopard, which is much *older* ...

My `sessionInfo`:

```
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gamm4_0.2-3  mgcv_1.8-6   nlme_3.1-120 lme4_1.1-7   Rcpp_0.11.5  Matrix_1.2-0

loaded via a namespace (and not attached):
[1] grid_3.1.2      lattice_0.20-31 MASS_7.3-40     minqa_1.2.4     nloptr_1.0.4    splines_3.1.2   tools_3.1.2    
```

**Comment by stevencarlislewalker** [comment]
Looks like the Yosemite thing is wrong, thanks Ben.

One other possibly wrong idea is to add `importFrom(lme4, REMLcrit)` to the `gamm4` `NAMESPACE`.  Maybe even `importFrom(lme4, REMLcrit, fixef, ranef)`, because `fixef` and `ranef` appear in `gamm4` with `lme4::` operators so maybe they can be removed too?

But this suggestion is admittedly weird because it should really be OS agnostic, so ...

**Comment by mmaechler** [comment]
Yes, this is all OS agnostic, really.  This must be a somehow wrong setup, specific to only some versions of R & MacOS.  Don't add import*() statements for now.  Rather we should ask for help on the  R-SIG-Mac mailing  list to find out more details about the broken setups.  I strongly claim that if regular R setups all dont show this problem, not even NOTEs in checks,  this must be something peculiar to "their" setup and not a bug in lme4.   Of course I could be wrong... but we (R developers, not just lme4 authors/users) should find out *what* the problem is .. so it can be fixed properly,  before we start trying to work around the bug (and make it go away for now instead of having it diagnosed and fixed properly).

**Comment by bbolker** [comment]
posted to `r-sig-mac`: http://article.gmane.org/gmane.comp.lang.r.mac/9417

**Comment by bbolker** [comment]
Since we haven't heard anything back about this in months, I'm going to close it.  Could be re-opened if someone comes back with a reproducible example or more information.
