### ISSUE TITLE
release 1.1-11

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#349]
Now that @mmaechler has updated the nlme version of `VarCorr` he is recommending that downstream package maintainers release a new version within a couple of weeks.

What are release-critical/desired items for the next release?

- I would **love** to clean up the false-positive convergence errors mess.  I propose increasing the gradient-checking tolerance to 0.01, and turning off Hessian computation entirely for models with >5000 observations (this makes this a little difficult because we can no longer compute the *scaled* gradient in that case).
- we should change the default glmer optimizer to BOBYQA throughout.
- ~~it would be nice to address #342~~ (thanks to @pitakakariki )

other thoughts?

**Comment by bbolker** [comment]
bump? anyone have opinions?

**Comment by pitakakariki** [comment]
You just need a name for the `Description` file right? "Peter Green".

My preference is to get the offset fixes onto CRAN sooner rather than later.

I'm also a tiny bit worried that changes to the default optimizer and convergence tests could have unintended consequences downstream, and might be enough to justify a version bump to 1.2. This is only a hunch though, I'm not familiar with those parts of the package.

**Comment by bbolker** [comment]
Well, it probably *is* wiser to wait (put it in the development version, test all the downstream packages, start telling people).  The main frustration is just that it's been so hard to overcome the activation energy ...
