### ISSUE TITLE
Too many random slopes

### ISSUE THREAD

**Issue by tmalsburg** [lme4/lme4#359]
Edit: never mind.

**Comment by bbolker** [comment]
Hmm. This is exactly what I would have expected to happen.  From the output above, `a`, `b`, `c` are factors with levels (`nota`,`a`), (`notb`,`b`), (`notc`,`c`).  Using the regular R formula expansion rules(i.e. calling `model.matrix`), formula `0+a:b:c` will expand to *all* combinations - the same number of parameters as `a*b*c`, but with different parameters (i.e. a separate parameter for each combination of levels rather than partitioning into main effects and interactive effects).

Can you clarify exactly what you want your levels to look like?  A strategy that always works, albeit one that can be tedious, is to construct your own numeric dummy variable for the combination of levels.  There is also a `dummy()` function that helps a little bit with this: I think that `dummy(interaction(a,b,c),levelsToKeep="a.b.c")` might do what you want.

I could of course be wrong, or confused.

You closed this just as I was writing my answer.  What did you find out?

**Comment by bbolker** [comment]
Are you willing to restore your question and state what your confusion was, in case it's useful for someone in the future?

**Comment by tmalsburg** [comment]
Thank you, Ben, for the response.  I removed the text because I realized that the issue was based on a misunderstanding and as such I though it is unsuitable for discussion in the issue tracker.  However, following your suggestion, I restored the description of the problem.

Using a numerical variable is exactly what I did to solve this.  I didn't know about the dummy function, thanks for pointing that out.
