### ISSUE TITLE
error compiling the new lme4

### ISSUE THREAD

**Issue by skanskan** [lme4/lme4#366]
Hello
When I run 
install_github("lme4/lme4",dependencies=TRUE)
I get this error:
namespace 'nlme' 3.1-122 is being loaded, but >= 3.1.123 is required

Though I have the last nlme version installed properly with:
install_github("cran/nlme",dependencies=TRUE)

In fact if you go to https://github.com/cran/nlme  you can see it doesn't exist the version 3.1.123

**Comment by bbolker** [comment]
I'm not quite sure how `install_github()` handles dependencies that are on CRAN rather than Github,  but `nlme` 3.1-124 *is* available on CRAN, e.g. look [here](https://cran.r-project.org/web/packages/nlme/index.html).  Try `install.packages("nlme"); install_github("lme4/lme4")`.  (The read-only mirror of CRAN you're pointing to hasn't updated its version of nlme since July 2015 ...)

**Comment by skanskan** [comment]
I pointed out that link because when I use install.packages("nlme") it installs nlme 3.1.122.
I'm using R 3.2.3, the Revolution R Open  version (because it includes the MKL libraries)

**Comment by skanskan** [comment]
OK, I got to it. I donwloaded the zip file and installed locally.

**Comment by bbolker** [comment]
what is `options("repos")` ?

**Comment by skanskan** [comment]
"https://mran.revolutionanalytics.com/snapshot/2016-01-01" 

I've installed that option because it's supposed to have some advantages.

How can I add several repos?
I guess that option only affects installing from github  because the settings under packages  say "University of California, Berkeley"

I'm afraid modifying the repos could break the compatibility with my R version.  Or maybe it's only noticeable on packages that use BLAS or some accelerated algebra...

**Comment by bbolker** [comment]
Well, if you install a frozen snapshot of CRAN you have to expect problems when you try to install updated packages!
I don't think any of the lme4 developers uses Revolution R, so compatibility problems with Revolution R are sort of up to you to solve.  The simplest solution, obviously, if you don't need or want any updated packages, is to stay with the frozen version.  Otherwise you have to take your chances.  `options("repos")` does allow you to have a vector of length >1 (i.e., more than one repository)
