### ISSUE TITLE
conditional variances via ranef when multiple terms per factor

### ISSUE THREAD

**Issue by sjPlot** [lme4/lme4#384]
Maybe this one is related to [this issue](https://github.com/lme4/lme4/issues/148), but I'm not sure whether it is not implemented yet or in general not possible to calculate?

```
library(lme4)
library(arm)
data("sleepstudy")
# Uncorrelated RE - Error
fm1 <- lmer(Reaction ~ Days + (1 | Subject) + (0 + Days|Subject), data = sleepstudy)
ranef(fm1, condVar = TRUE)
```

> Warnmeldung:
> In ranef.merMod(fm1, condVar = TRUE) :
>   conditional variances not currently available via ranef when there are multiple terms per factor

**Comment by bbolker** [comment]
Don't know offhand, although I suspect it's an annoying bookkeeping problem rather than a fundamental theoretical/computational difficulty. There are, unfortunately, several issues in this category ("not fundamentally impossible but would require a significant investment that's not very likely to happen in the absence of a really strong incentive"), such as implementing Gauss-Hermite quadrature for vector-valued random effects (#123) ...

**Comment by bbolker** [comment]
this should be available now in the development version (soon to be 1.1-18)
