### ISSUE TITLE
Issue in predict function 

### ISSUE THREAD

**Issue by Fablepongiste** [lme4/lme4#393]
I got this error when using predict function of lme4. 
Error in validObject(.Object) : 
  invalid class “dgCMatrix” object: invalid object for slot "i" in class "dgCMatrix": got class "numeric", should be or extend class "integer"

I managed to reproduce it on an example. 

library(lme4)

n <- 100

res <- sample(c(0,1), n, replace = TRUE)
firstSet <- sample(c(0,1), n, replace = TRUE)
var1 <- rnorm(n)
var2 <- rnorm(n)
player <- sample(c("a", "b", "c", "d", "e", "f"), n, replace = TRUE)

data <- data.frame(res, firstSet, var1, var2, player)

fm1 <- glmer(res ~ 0 + var1 + var2 + (0 + firstSet|player), data, family="binomial")
predict(fm1, newdata=data, type="response")

testData <- data

testData$var1 <- 0
testData$var2 <- 0
testData$firstSet <- 0
predict(fm1, newdata=testData, type="response")

This seems to happen when the dataset passed in predict contains a lot of 0 and consequently the predict matrices becomes sparse ? Only solution I found was to ensure the prediction dataset has a row full of 1 ...  

Using last version of lme4 and Matrix on linux

sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-suse-linux-gnu (64-bit)
Running under: SUSE Linux Enterprise Desktop 12 SP1

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8  
 [6] LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C  
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lme4_1.1-11  Matrix_1.2-6

loaded via a namespace (and not attached):
[1] minqa_1.2.4     MASS_7.3-45     tools_3.2.3     Rcpp_0.12.5     splines_3.2.3   nlme_3.1-126    grid_3.2.3      nloptr_1.0.4    lattice_0.20-33

**Comment by Fablepongiste** [comment]
This however works 
testData$var1 <- 0
testData$var2 <- 0
testData$firstSet <- 1
predict(fm1, newdata=testData, type="response")

Which means it is the random effect causing issue if full of 0

**Comment by RobertBChatfield** [comment]
I get the same error, and once again, one variable "x" was uniformly 0
formula: lmer( y ~ x + (x - 1 | species.type) + ( 1 | Fire.Type) + ( 1 | id) + 1 + ( 1 | YrDay)
By instead setting x uniformly  to a small value (0.01) ... where in the original estimation  the minimum of x was about 2.3,  
the prediction  worked:, in this case:
predict(first.spectype.lmer,newdata=sim.0.first.long.dat)

Thanks for the note: this seems to confirm your hunch.

**Comment by bbolker** [comment]
I'll try to look into this.  Maybe an issue with non-structural zeros getting turned into structural zeros within a sparse matrix and thus changing its structure in some surprising way.

**Comment by Fablepongiste** [comment]
I think that's the case @bolker problem with sparse matrix.

**Comment by bbolker** [comment]
I think this actually a bug in `Matrix::KhatriRao` (paging @mmaechler ...) Minimal example:

```
library(Matrix)
mm <- matrix(0,ncol=10,nrow=1)
mm0 <- matrix(c(1,rep(0,9)),ncol=10)
sm0 <- matrix(rep(c(1,0,1,0,1),4),nrow=2,ncol=10)
KhatriRao(sm0,mm0)  ## works
KhatriRao(sm0,mm)    ## fails
```

The proximal problem is that on line 32 of `Matrix/R/KhatriRao.R` we have this:

```
 i2 <- unlist(rep(split.default(Y@i,yj), xn.yp))
```
when everything is empty `Y@i==integer(0); yj==factor(0); xn.yp=integer(0)` we end up `unlist()`ing an empty list, which becomes NULL; when we compute `newi <- i1*n2 + i2` on l. 34, we end up with `numeric(0)` instead of `integer(0)` ...

changing l. 32 to 

```
    i2 <- as.integer(unlist(rep(split.default(Y@i,yj), xn.yp)))
```

seems to fix the problem.  Hard to see what unintended consequences that could have ...

If this is the case, we'll have to work around it or wait until the next release of Matrix.

**Comment by Fablepongiste** [comment]
Have you opened an issue in the Matrix package ?

**Comment by bbolker** [comment]
No - we could, but @mmaechler is the Matrix maintainer and will probably respond here fairly soon. If not, feel free to open an issue in Matrix; since it's a recommended package (maintained by R-core) and the `BugReports:` field in the DESCRIPTION is NA, http://bugs.r-project.org would be the right place ...

**Comment by mmaechler** [comment]
Thanks a lot, @bbolker , for your trackdown  of the KathriRao()  border case bug.
As I am finding, I'd rather use an  if(.) for these cases, rather than an extraneous  as.integer(.).

A new `Matrix` release to CRAN is possible of course, though always a lot of CPU on the CRAN servers for all recursive dependency checks.   I will try it still.

 BTW, I think we should keep a 'bordercase' / trivial example also in our lme4 regression checks.

**Comment by Fablepongiste** [comment]
Should we close this issue, as seems to be fixed with last Matrix release ?

**Comment by mmaechler** [comment]
It was even fixed with one Matrix release earlier ..   Thanks for fixing it here, too.
