### ISSUE TITLE
Make allFit() directly available in lme4 

### ISSUE THREAD

**Issue by twolodzko** [lme4/lme4#433]
Could you make `fitAll` function (it probably needs renaming) directly available in lme4? If you do not want to add additional dependencies, you could first use `requireNamespace` to test which packages are available and then use it only with the available optimizers.

**Comment by bbolker** [comment]
hmm .  What's so hard about `source(system.file("utils", "allFit.R", package="lme4"))`  (as suggested in `?convergence`) ?

The main reason I don't want to do this is that it conflicts a bit with a **long** overdue clean-up of the convergence-checking and warnings, which will rely much more heavily on optimizer warnings (i.e. from optim(), bobyqa(), etc.) and otherwise

- significantly increase the warning tolerance
- (probably) eliminate post-convergence checking for large data sets (slow & many more false positives)
- change the default optimizer, probably to the nloptr version of BOBYQA
- add messages (prob not warnings) for singular fits, and disable convergence testing thereof unless we can properly use the bounded versions of KKT conditions

**Comment by twolodzko** [comment]
@bbolker Well, yes you can do this, but it took me a while to learn about existence of such function. Moreover, in the docs it is described only in the examples (I missed it). Making it directly available, plus documenting its behavior, would make life of lme4 users much easier.

**Comment by mmaechler** [comment]
I agree with @bbolker .   To make `allFit()` even a bit easier to find, I have added text to mention it already before the examples section (thanks to @twolodzko for the "hint").

Marked as wishlist, so we may revisit in a future where there will hopefully be less need for it.
