### ISSUE TITLE
model.frame(fixed.only = TRUE) throws error for non-syntactical variable names

### ISSUE THREAD

**Issue by strengejacke** [lme4/lme4#441]
``` r
library(lme4)
#> Loading required package: Matrix
d <- sleepstudy

m <- lmer(Reaction ~ Days + (Days | Subject), d)
head(model.frame(m, fixed.only = TRUE))
#>   Reaction Days
#> 1 249.5600    0
#> 2 258.7047    1
#> 3 250.8006    2
#> 4 321.4398    3
#> 5 356.8519    4
#> 6 414.6901    5

names(d)[1] <- "Reaction Time"
m <- lmer(`Reaction Time` ~ Days + (Days | Subject), d)
model.frame(m, fixed.only = TRUE)
#> Error in `[.data.frame`(fr, vars): undefined columns selected
```

**Comment by strengejacke** [comment]
( `model.frame(m, fixed.only = F)` works for the above model...)

**Comment by bbolker** [comment]
I will see what I can figure out.  Although I can see some of the attractions, this (putting non-syntactic names in a formula) does feel like asking for trouble!

**Comment by bbolker** [comment]
OK, here's the problem. The definition of `lme4:::model.frame.merMod` is:

```
function (formula, fixed.only = FALSE, ...) 
{
    fr <- formula@frame
    if (fixed.only) {
        ff <- formula(formula, fixed.only = TRUE)
        vars <- rownames(attr(terms.formula(ff), "factors"))
        fr <- fr[vars]
    }
    fr
}
```

In this example, `vars` ends up having a back-tick in the variable name (<code>c("\`Reaction Time\`","Days" )</code>, while the row names of the model frame don't (`c("Reaction Time","Days")`).

I could hack around this by adding <code>gsub("\`","",vars)</code>, but it feels ugly/*ad hoc*.

It occurs to me that `vars <- all.vars(ff)` *might* work fine; it seems to get what we want in this case.  I'm a little nervous because I don't know how complete our test coverage is in this case ... (I *still* don't have complete reverse-dependency checking set up ...)

**Comment by bbolker** [comment]
uh-oh.  [This SO question](https://stackoverflow.com/questions/18017765/extract-variables-in-formula-from-a-data-frame) explains why `all.vars()` doesn't work ...

**Comment by strengejacke** [comment]
This issue is not of high priority for me, I was just wondering why it worked with `fixed.only = F`, but not for `fixed.only = T`.

**Comment by bbolker** [comment]
I went ahead and fixed this with `gsub()`. It's only a tiny bit more technical debt ...

**Comment by mmaechler** [comment]
Hmm, your proposed  `gsub()`  above would/could be wrong though: It replaces all back quotes but it should only replaces at beginning and end:  contrived ("non syntactic") var names can contain backqoutes also in the middle etc.    I feel such patch ups are rather error prone and should be approached in a more principled way,  using well defined semantics ideally via base functions.  Maybe 
all.vars() needs a new optional argument there, or we don't allow certain names, etc.     I agree with the general approach that var names should work in those cases they work with `lm()`.

**Comment by mmaechler** [comment]
Really.  As I've said many times in the past -- and it is still true even if people don't believe it:  All String handling is error-prone in such cases and "wrong by design".
Look at  `model.frame.default()`  and  `model.frame.lm()`:  They use `substitute()`  but **not**  `sub()` or `gsub()` or similar "wrong by design"--techniques.

**Comment by bbolker** [comment]
I agree, in principle, and have to admit that I have often made better by respecting this advice.

That said, I have a couple of complaints/questions about the design of `terms.object()` (which presumably trace back to `model.frame()`, which is I think where the terms objects get constructed ...

- in the case of non-syntactic variable names, why are enclosing backticks preserved in the rownames of the "factor" attribute of the terms but not in the names of the model frame?
- why is this attribute an empty data frame (as documented, but I'm curious about the reason) when there are no non-offset, non-intercept terms on the RHS of the formula, but includes the response variable when there are any non-trivial terms?

Do you have a better strategy in mind?  I have yet to figure out how to do achieve this goal *simply* using base functions (and I have tried).

I can think of two alternatives:

- walk the expression and deparse elements appropriately. (We *must* end with deparsed objects, because we need to match them to columns of the data frame.) This is a huge pain because we would have to deal with WIlkinson-Rogers expansion -- exactly what `model.frame` and friends are designed to do.
- Probably better: [here](https://github.com/lme4/lme4/blob/master/R/modular.R#L679) we have the fixed-effect model frame in hand.  Store its names as an attribute of the formula ...

```
    ## non-syntactic names
    d <- sleepstudy
    names(d)[1] <- "Reaction Time"
        tf <- function(f,d) {
            return(rownames(attr(terms(f,data=d),"factor")))
        }
        tf(Reaction~1,sleepstudy) ## NULL
        tf(Reaction~Days,sleepstudy) ## "Reaction" "Days"
        tf(`Reaction Time`~Days,sleepstudy) ## "`Reaction Time`" "Days"
        tf(Reaction~log(1+Days),sleepstudy) ## "Reaction" "log(1 + Days)"
```

**Comment by bbolker** [comment]
after breaking things a couple of times I think this is now resolved.

**Comment by mmaechler** [comment]
excellent. Indeed storing and reusing is best!
