### ISSUE TITLE
drop1 only dropping highest order terms (lmer)

### ISSUE THREAD

**Issue by respatte** [lme4/lme4#459]
I recently discovered `drop1` and was wondering if I could take a look at the code to write a parallel version of it to use on a rather big dataset (eye-tracking, growth curve analysis that currently lasts for about 10 hours for the full model). So I started looking at the lines and running them manually to understand what each did and how to change them.

That's how I realised that `scope.drop`, used in `drop1` to determine the list of terms to sequentially drop from the models, didn't give me a full list of effects, but only the terms of highest order. For the model I'm mentioning at the start, I have

```
LT.time_course_aois.GCA <- lmer(ArcSin ~ (Condition*Part)*
                                  (ot1 + ot2 + ot3 + ot4 + ot5 + ot6 + ot7) +
                                  (1 + Part +
                                     ot1 + ot2 + ot3 + ot4 + ot5 + ot6 + ot7 | Participant) +
                                  (1 | Stimulus) +
                                  (1| StiLabel),
                                data = LT.time_course_aois.first_last, REML = F,
                                control = lmerControl(optCtrl = list(maxfun = 100000)))
drop.scope(LT.time_course_aois.GCA)
## [1] "Condition:Part:ot1" "Condition:Part:ot2" "Condition:Part:ot3" "Condition:Part:ot4"
## "Condition:Part:ot5" "Condition:Part:ot6" "Condition:Part:ot7"
```

To give you a working example, let's consider the simple model bellow (with [this data](https://justpaste.it/1ik5d)):

```
# prop <- structure(...) from link above
prop.lmer.0 <- lmer(ArcSin ~ Part*Condition + (1 | Participant), data = prop)
```

Now what I would like to do is compare the intercept-only model with the `Part`, `Part+Condition` and `Part+Condition+Part:Condition` models to see which effects improve model fit:

```
prop.lmer.1 <- update(prop.lmer.0, . ~ . - Part:Condition)
prop.lmer.2 <- update(prop.lmer.1, . ~ . - Condition)
prop.lmer.3 <- update(prop.lmer.2, . ~ . - Part)
prop.lmer.comp <- anova(prop.lmer.3,
                        prop.lmer.2,
                        prop.lmer.1,
                        prop.lmer.0)
## Data: prop
## Models:
## prop.lmer.3: ArcSin ~ (1 | Participant)
## prop.lmer.2: ArcSin ~ Part + (1 | Participant)
## prop.lmer.1: ArcSin ~ Part + Condition + (1 | Participant)
## prop.lmer.0: ArcSin ~ Part * Condition + (1 | Participant)
##             Df    AIC    BIC  logLik deviance   Chisq Chi Df Pr(>Chisq)    
## prop.lmer.3  3 22.961 28.511 -8.4804  16.9608                              
## prop.lmer.2  4 14.065 21.466 -3.0326   6.0652 10.8956      1  0.0009639 ***
## prop.lmer.1  5 13.213 22.464 -1.6066   3.2131  2.8521      1  0.0912551 .  
## prop.lmer.0  6 14.783 25.884 -1.3916   2.7833  0.4298      1  0.5120718    
## ---
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

However `drop1`, using `scope.drop`, only gives me the difference between the original model and the deletion of `Part:Condition`:

```
drop1(prop.lmer.0)
## Single term deletions
## 
## Model:
## ArcSin ~ Part * Condition + (1 | Participant)
##                Df    AIC
## <none>            14.783
## Part:Condition  1 13.213
```

Note that I just checked with `drop1.lm`, I get the same issue (maybe not so surprisingly). Is this actually the desired behaviour and I have been doing term-deletion wrong all this time? Or did something change recently affecting `drop.scope`?

**Edit:** after 10 more minutes searching for an explanation, I found the solution: I simply needed to give the `scope` argument `~.` to `drop1`... I'm now wondering, is there a reason why this is not the default behaviour?

**Comment by dmbates** [comment]
In most cases the it doesn't make sense to test a main effect while retaining an interaction.  Consider a simple example where the effect of a condition is large for males but not large for females.  In other words there is a significant interaction of `Sex` and `Cond`.  If you fit `y ~ 1 + Sex + Cond + Sex:Cond` and compare to `y ~ 1 + Sex + Sex:Cond` you get a significant difference if the reference level for `Sex` is male but not if the reference level is female.  This is why statisticians retain lower order interactions or main effects when there is a significant higher order interaction.

**Comment by dmbates** [comment]
In other words, `drop1` is doing the thing that makes sense to statisticians.

**Comment by bbolker** [comment]
There's a famous (?) rant on this subject in Venables's [exegeses on linear models](https://www.stats.ox.ac.uk/pub/MASS3/Exegeses.pdf). From section 5.2:

> The irony is, of course, that Type III sums of squares were available all along if only people
understood what they really were and how to get them. If the call to drop1 contains any formula as the second argument, the sections of the model matrix corresponding to all non-intercept terms are omitted seriatim from the model, giving some sort of test for a main effect: `drop1(gen.1, . ̃.)`

I agree that a parallel version of `drop1` would be a nice enhancement. It's a little bit scary because getting the right evaluation context for fitting the updated models is tricky, and parallel evaluation might make it trickier.  (It would also be nice to allow for dropping of random effects ...)

Have you tried either `glmmTMB` (potentially faster for models with large of variance-covariance parameters) or `MixedModels.jl` (generally faster)? There would be some overhead to trying a new platform, and the downstream tools (prediction/marginal effects/inference/etc etc) are not as well developed, but they might cut the fitting times down considerably ...

**Comment by respatte** [comment]
Thanks for the insightful comments! Just to check I really understand, is it the case then that `drop1` does something different to the term deletion I do by hand? In my term deletion, I always add all the terms of order *n* before adding any terms of order *n-1*, therefore I don't have the issue you are mentioning, which is sort of reassuring. Am I right understanding that `drop1` instead deletes one term from the model only and compare all those model with one term deleted per model to the original model, thus leading to the issue you are talking about? (I have to admit, the proper stats talking still remains a little confusing to me)

Thanks for the hint on other possibly faster packages, I will definitely try them!

**Comment by runehaubo** [comment]
There seems to be two things going on here: the tests that `drop1` produce and the sequence of tests that you are looking for (and expecting?). You describe the latter as "Now what I would like to do is compare the intercept-only model with the `Part`, `Part+Condition` and `Part+Condition+Part:Condition` models to see which effects improve model fit". This sequence of tests is known Type I tests/hypotheses/anova, also known as a sequential anova table and that is the  SSQ decomposition that `anova.lm` and `anova.merMod` produce. 

`drop1` is not designed to produce the type I anova table, but using `anova.merMod` while providing the SSQ decomposition does not provide any p-values for the F-statistics.

Using the lmerTest package using your example data I get:
````
> prop.lmer.0 <- lmer(ArcSin ~ Part*Condition + (1 | Participant), data = prop)
Warning messages:
1: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
   Hessian is numerically singular: parameters are not uniquely determined
2: In as_lmerModLmerTest(model) :
  Model may not have converged with 1 eigenvalue close to zero: -1.9e-09
> anova(prop.lmer.0, type=1)
Type I Analysis of Variance Table with Satterthwaite's method
                Sum Sq Mean Sq NumDF DenDF F value   Pr(>F)   
Part           0.80480 0.80480     1    43 11.8527 0.001295 **
Condition      0.07523 0.07523     1    43  1.1080 0.298402   
Part:Condition 0.02682 0.02682     1    43  0.3951 0.532980   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> drop1(prop.lmer.0)
Single term deletions using Satterthwaite's method:

Model:
ArcSin ~ Part * Condition + (1 | Participant)
                 Sum Sq  Mean Sq NumDF DenDF F value Pr(>F)
Part:Condition 0.026824 0.026824     1    43  0.3951  0.533
````
You need the development version to do this:
````
library("devtools")
install_github("runehaubo/lmerTestR")
````
Here you get the more accurate F-tests instead of the asymptotic likelihood ratio tests (in this apparently balanced(?) case the F-tests are even _exact_ tests). Also note that `lmerTest::drop1` also produces an F-test: not only is this test more accurate than the likelihood ratio test by `lme4::drop1`, it also avoids refitting the model. 

I hope it is ok that I bring lmerTest (which I am currently working on) into the discussion in this forum.

Cheers
Rune

**Comment by respatte** [comment]
Thanks for the very detailed explanation, I guess I should now do some more reading on Type I and Type III tests, we don't seem to have an extensive knowledge of that in my (psychology) department!
