### ISSUE TITLE
Stratified random intercept

### ISSUE THREAD

**Issue by jgellar** [lme4/lme4#466]
I would like to fit a mixed model to two-level data, where the random effects (intercepts only) are constrained to be normally distributed around 0 for each level of a categorical variable. Is this possible? The closest thing I could think of is to include a random effect for each level of the categorical variable, where the grouping variables are all the same whenever the value of the categorical variable in the data does not match the group the variable is supposed to represent.

For example, suppose you have a variable `group` with lots of values, and a binary group-level variable `treatment`. You want to include random intercepts for group, but ensure that the random intercepts are normally distributed with mean 0, separately for treated and control groups. I could create `group0` which is equal to `group` when `treatment==0`, and equals something else ("ref") when `treatment==1`, and similarly for `group1`, and then fit the model
```
lmer(Y ~ (1|group0) + (1|group1), data = d)
```
But this is not exactly the model I want to fit because it will include RE's for the "ref" levels. Is there an easy alternative using lmer, or do I have to fit the model in a bayesian framework?

**Comment by runehaubo** [comment]
You can fit this model with

    lmer(Y ~ (treatment | group), data=d)

The correlation/covariance in the 2x2 covariance matrix is not identifiable but you can ignore it (what ever value turns up). But be careful: the model is over-parameterised and you have to adjust for it in likelihood ratio tests etc. You will probably also get convergence warnings since the Hessian will be singular but you should be ok as long as the gradient is small. I have done this previously but of course there is no guarantee that it also works for you data.

This is the situation where I wish the the double bar would just estimate the parameters in a diagonal covariance matrix for the random effects: `lmer(Y ~ (treatment || group), data=d)` but I don't think that works....

The model can, as far as I recall, also be fitted with `nlme::lme` - I think you need a `pdBlocked` structure with a list of `pdDiag` matrices, but my memory may have mixed up the details.

Cheers
Rune

**Comment by bbolker** [comment]
Other options to fit a diagonal variance-covariance matrix based on a factor:

- use `afex::mixed`, which rearranges things so the double-bar operator really works as desired (there is a pull request to integrate this functionality into `lme4`, which I haven't given enough attention to yet)
- use the `dummy()` functionality (see `?dummy`)

I'm going to close this now - the `r-sig-mixed-models@r-project.org` mailing list is  a better venue for general "how do I ... ?" questions like this
