### ISSUE TITLE
Controlling number of cores/cpus with lmer

### ISSUE THREAD

**Issue by bacms2** [lme4/lme4#492]
We are having issues with one of our HPC users running an R scripts that performs lmer calculation. Is there any way I can limit the number of cpus the lmer function can grab? I see the ncpus can be set for other functions but setting it on lmer seems to be doing nothing.

**Comment by bbolker** [comment]
lmer doesn't run in parallel at the R level (the only pieces of the lme4 package that do so are the embarrassingly parallel bits like likelihood profiling and bootstrapping), so the only reason I can think of that it would grab more than one core would be if you're using a fancy multi-threaded version of BLAS ... ? In which case I would try out the [RhpbcBLASctl package](https://cran.r-project.org/web/packages/RhpcBLASctl/index.html) ...

(Just to be clear, is the problem that it's grabbing too *many* cores/CPUs, or too few?)

**Comment by bacms2** [comment]
> lmer doesn't run in parallel at the R level (the only pieces of the lme4 package that do so are the embarrassingly parallel bits like likelihood profiling and bootstrapping), so the only reason I can think of that it would grab more than one core would be if you're using a fancy multi-threaded version of BLAS ... ? In which case I would try out the [RhpbcBLASctl package](https://cran.r-project.org/web/packages/RhpcBLASctl/index.html) ...
> 
> (Just to be clear, is the problem that it's grabbing too _many_ cores/CPUs, or too few?)

Definitely too many. Here is I did to replicate this:
Start R and grab the process id
`
$ sh -c 'echo $$; exec R'
190923
`
Then run the following R code
`> library(lme4)
Loading required package: Matrix
> phens <- read.table("Pheno_MAGIC_height.txt" , header = T)
> genos <- read.table("MAGIC_estfnd_0.98.txt", header = T)
> ped <- read.table("pedigree_643.txt", header = T)
> map <- read.table("MAGIC_IBD_dd_0.98_map.txt", header = T)
>   result.SNP.trait<-matrix(NA,nrow=320300,ncol=29)
>   funn<-ped$funnel
>   plnt<-factor(ped$plant)
>   Y<-phens[,1]
>   j = 1
>   l=((j-1)*100)+1
>   m=l+99
>   k=1
>   q = 1
>   for(q in l:m){
+     for(i in 1:3203){
+       SNP1<-as.factor(genos[,q])
+       SNP2<-as.factor(genos[,i])
+       Y<-phens[,1]
+       fred<-lmer(Y~(1|funn)+SNP1*SNP2,ncpus=1,cl=NULL)
+ }
+ }
`
Finally monitor the cpu usage with top
```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                       
190923 murrayr   20   0 2930592 199776  11584 R  **6114**  0.0  20:23.63 R      
```

**Comment by bbolker** [comment]
Thanks for the example.  A few points:

- I'm 99.9% sure that the issue derives from BLAS threading, not any explicit parallelization within `lmer`. As I said above, `lmer` doesn't run in parallel at all - in fact, you should be seeing warning messages about `extra argument(s) ‘cl’, ‘ncpus’ disregarded`
- have you tried experimenting with [RhpcBLASctl](https://cran.r-project.org/web/packages/RhpcBLASctl/index.html) as suggested above?
- the example isn't reproducible unless one has access to the data files (as the problem is very unlikely to have anything to do with the details of the data, we could write code to simulate data that look like this - but it would be easier if we didn't have to). How many observations are there (i.e. how many rows in `phens`?) I'm guessing that `SNP1` and `SNP2` are gene scores (0-2)? How many levels does `funn` have?
-  can we see the results of `sessionInfo()` please? In particular, there should be a couple of lines describing your BLAS setup.

**Comment by bacms2** [comment]
You were absolutely right. Changing the number of threads for BLAS with RhpcBLASctl solved the problem. 

The input files are from a colleague so I will ask for more details and report later today. 

Thank you very much for you help

**Comment by bbolker** [comment]
Well, if the problem is solved I think we don't really need the reproducible example ...

**Comment by slowkow** [comment]
I think I figured it out. This seems to work for me on my machine:

```r
library(RhpcBLASctl)
library(lme4)

blas_set_num_threads(2)

res <- glmer(...)
```

Now I see 200% CPU usage instead of 6000% CPU usage.

<details><summary>sessionInfo()</summary><pre>

> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] RhpcBLASctl_0.20-137 readxl_1.3.1         ggbeeswarm_0.6.0
 [4] scales_1.1.1         ggrepel_0.9.0        data.table_1.13.6
 [7] forcats_0.5.0        stringr_1.4.0        dplyr_1.0.4
[10] purrr_0.3.4          readr_1.4.0          tidyr_1.1.2
[13] tibble_3.0.6         ggplot2_3.3.2.9000   tidyverse_1.3.0
[16] magrittr_2.0.1       lme4_1.1-23          Matrix_1.3-2
[19] glue_1.4.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6         lubridate_1.7.9    lattice_0.20-41    ps_1.5.0
 [5] assertthat_0.2.1   R6_2.5.0           cellranger_1.1.0   backports_1.2.1
 [9] reprex_0.3.0       httr_1.4.2         pillar_1.4.7       rlang_0.4.10
[13] minqa_1.2.4        rstudioapi_0.13    nloptr_1.2.2.2     blob_1.2.1
[17] R.oo_1.24.0        R.utils_2.10.1     splines_4.0.4      statmod_1.4.35
[21] pheatmap_1.0.12    munsell_0.5.0      broom_0.5.6        janitor_2.0.1
[25] compiler_4.0.4     vipor_0.4.5        modelr_0.1.8       pkgconfig_2.0.3
[29] tidyselect_1.1.0   crayon_1.4.1       dbplyr_1.4.4       withr_2.4.1
[33] R.methodsS3_1.8.1  MASS_7.3-53.1      grid_4.0.4         nlme_3.1-152
[37] jsonlite_1.7.2     gtable_0.3.0       lifecycle_1.0.0    DBI_1.1.1
[41] pacman_0.5.1       cli_2.3.0          stringi_1.5.3      fs_1.5.0
[45] snakecase_0.11.0   xml2_1.3.2         ellipsis_0.3.1     generics_0.1.0
[49] vctrs_0.3.6        boot_1.3-27        RColorBrewer_1.1-2 tools_4.0.4
[53] beeswarm_0.2.3     hms_1.0.0          colorspace_2.0-0   rvest_0.3.5
[57] haven_2.3.1
</pre></details>

**Comment by nadavrap** [comment]
On MacOS (MacBook pro with M1 chip), `glmer` utilize a single thread, and editing using `blas_set_num_threads(2)` doesn't seem to have an effect.

**Comment by nadavrap** [comment]
```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin21.5.0 (64-bit)
Running under: macOS Monterey 12.5

Matrix products: default
BLAS:   /opt/homebrew/Cellar/openblas/0.3.20/lib/libopenblasp-r0.3.20.dylib
LAPACK: /opt/homebrew/Cellar/r/4.2.1/lib/R/lib/libRlapack.dylib

locale:
[1] C/UTF-8/C/C/C/C
```

**Comment by bbolker** [comment]
To be honest I'm not sure which BLAS versions are multithreaded and which aren't. I have `BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so` and definitely see an effect of using `RhpcBLASctl::blas_set_num_threads()`. I will repeat that **none of this stuff is explicitly implemented at the lme4 level** -- everything is going on at the level of the BLAS installation, so this isn't really our (== lme4 developers') problem ... maybe check out https://cran.r-project.org/bin/macosx/RMacOSX-FAQ.html#Which-BLAS-is-used-and-how-can-it-be-changed_003f ...?
