### ISSUE TITLE
`ggstatsplot` tests failing with `1.1-20` - no notification received

### ISSUE THREAD

**Issue by IndrajeetPatil** [lme4/lme4#500]
Hi, my package tests are failing since `lme4 1.1-20` appeared on `CRAN` (https://cran.r-project.org/web/checks/check_results_ggstatsplot.html). 

![image](https://user-images.githubusercontent.com/11330453/52213814-25ef7e00-285e-11e9-9f07-65b05e243668.png)

I discovered this only when I updated `lme4` version on my local computer and my tests failed. I am surprised that I didn't receive any notification about this. The `CRAN` policy states that:

> "If an update will change the package’s API and hence affect packages 
> depending on it, it is expected that you will contact the maintainers of 
> affected packages and suggest changes, and give them time (at least 2 
> weeks, ideally more) to prepare updates before submitting your updated 
> package. Do mention in the submission email which packages are affected 
> and that their maintainers have been informed. In order to derive the 
> reverse dependencies of a package including the addresses of maintainers 
> who have to be notified upon changes, the function 
> reverse_dependencies_with_maintainers is available from the developer 
> website."
> 

Does `lme4` not run `revdepcheck`?

**Comment by bbolker** [comment]
Sorry about that. We **did** run `revdepcheck`, but only on one platform (see below). The lesson for the future is that we should e-mail all package maintainers directly when we're making this sort of change; it's too hard for us to catch everything, and maintainers deserve more of a heads-up.

The problem is that ([as mentioned on r-sig-mixed-models](https://stat.ethz.ch/pipermail/r-sig-mixed-models/2019q1/027565.html)) we've changed the default optimizer for `lmer`. Your choices for fixing the problem are setting the optimizer back to the previous default (`control=lmerControl(optimizer="bobyqa")`) or adjusting test tolerances; looking at the specific error you're getting it seems like the former will be easier.

Your package fails non-trivially on fedora-clang (the problems on solaris and windows-oldrel seem unrelated). We only ran on r-devel-linux 64-bit with gcc, because that's the only test platform we have available.  We missed two problems we should have caught on that platform (with `robustlmm` and `rstap`; long story). CRAN told us about 5 more packages that failed tests on Windows, and we've been in contact with those maintainers. It's a little surprising that CRAN missed `ggstatsplot` too ...

**Comment by IndrajeetPatil** [comment]
Ah, I see. I will modify the tests. I was just worried that CRAN will ask me to submit a new version when I am not prepared for it. But, since the tests are failing on very few platforms, maybe they won't.

I am working on a Windows machine with `3.6.0`. Here is my session information-
``` r
sessioninfo::session_info(include_base = TRUE)
#> - Session info ----------------------------------------------------------
#>  setting  value                                             
#>  version  R Under development (unstable) (2018-11-30 r75724)
#>  os       Windows 10 x64                                    
#>  system   x86_64, mingw32                                   
#>  ui       RTerm                                             
#>  language (EN)                                              
#>  collate  English_United States.1252                        
#>  ctype    English_United States.1252                        
#>  tz       America/New_York                                  
#>  date     2019-02-04                                        
#> 
#> - Packages --------------------------------------------------------------
#>  ! package     * version    date       lib source                    
#>    assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.1)            
#>    base        * 3.6.0      2018-12-01 [?] local                     
#>    cli           1.0.1.9000 2019-01-20 [1] Github (r-lib/cli@94e2fc5)
#>  P compiler      3.6.0      2018-12-01 [2] local                     
#>    crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)            
#>  P datasets    * 3.6.0      2018-12-01 [2] local                     
#>    digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.1)            
#>    evaluate      0.12       2018-10-09 [1] CRAN (R 3.5.1)            
#>  P graphics    * 3.6.0      2018-12-01 [2] local                     
#>  P grDevices   * 3.6.0      2018-12-01 [2] local                     
#>    highr         0.7        2018-06-09 [1] CRAN (R 3.5.1)            
#>    htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.1)            
#>    knitr         1.21       2018-12-10 [1] CRAN (R 3.6.0)            
#>    magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.1)            
#>  P methods     * 3.6.0      2018-12-01 [2] local                     
#>    Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.6.0)            
#>    rmarkdown     1.11       2018-12-08 [1] CRAN (R 3.6.0)            
#>    sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)            
#>  P stats       * 3.6.0      2018-12-01 [2] local                     
#>    stringi       1.2.4      2018-07-20 [1] CRAN (R 3.6.0)            
#>    stringr       1.3.1      2018-05-10 [1] CRAN (R 3.5.1)            
#>  P tools         3.6.0      2018-12-01 [2] local                     
#>  P utils       * 3.6.0      2018-12-01 [2] local                     
#>    withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)            
#>    xfun          0.4        2018-10-23 [1] CRAN (R 3.6.0)            
#>    yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.1)            
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-devel/library
#> 
#>  P -- Loaded and on-disk path mismatch.
```

<sup>Created on 2019-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
