### ISSUE TITLE
terminology in 'singular' fit message: suggestion

### ISSUE THREAD

**Issue by tslumley** [lme4/lme4#502]
The new message to warn about fits where some linear combination of the variance component is zero looks really useful.  I'm writing to suggest that the name be changed, maybe to "boundary fit" or "zero variances" or something.  The word "singular" in "singular fit" suggests (to me) non-identifiability, rather than the estimate being on the boundary of the parameter space.  I assume 'singular' was used because the matrix that transforms the iid latent variables u to the random effects b (in Laird & Ware notation) is singular, but this matrix seems to be to be more part of the computational mechanism than part of the model.

**Comment by bbolker** [comment]
@dmbates what do you think? ("boundary fit" would be better than "zero variances", I think, because it's easy to get a singular fit with none of the random effects variances being zero [one could argue that *the variance of some linear combination of terms* is zero, but that feels like a stretch]. I am a little concerned because the terminology is pretty well disseminated in the R/mixed-models universe at this point ...

**Comment by bachlaw** [comment]
I agree. I was surprised when the new message showed up and the model still seemed to otherwise fit normally. A warning like “at least 1 group variance of zero; possible boundary condition” or similar for me would be both more informative and direct people who researched it toward blme or full Bayes.

But if “singular fit” is a term that has some special meaning in this context I don’t want to create confusion either.

Jonathan

Sent from my iPhone

On Feb 12, 2019, at 12:03 AM, Thomas Lumley <notifications@github.com<mailto:notifications@github.com>> wrote:


The new message to warn about fits where some linear combination of the variance component is zero looks really useful. I'm writing to suggest that the name be changed, maybe to "boundary fit" or "zero variances" or something. The word "singular" in "singular fit" suggests (to me) non-identifiability, rather than the estimate being on the boundary of the parameter space. I assume 'singular' was used because the matrix that transforms the iid latent variables u to the random effects b (in Laird & Ware notation) is singular, but this matrix seems to be to be more part of the computational mechanism than part of the model.

**Comment by dmbates** [comment]
@tslumley Actually the reason for using the word singular is because the variance-covariance matrix for the random effects is singular but that also corresponds to its Cholesky factor being singular.

I agree that the word "singular" may not be obvious to everyone.  "Boundary fit" may be a better explanation.   As Ben has pointed out "zero variances" may seem confusing when none of the variances of the random effects are zero, it is only the variances of some linear combinations that are zero.

I guess that of the options I would prefer "boundary fit".  

@bachlaw Why would one want to use Bayesian methods if the fit is on the boundary?  There is some confusion about what an estimated variance of zero for random effects or linear combinations of random effects means.  It does not mean that there is no variance between the groups - it just means that there is no *excess* variance observed in addition to the variability induced by the residual noise term.  If you fit a simple random effects model to the `Dyestuff2` data from the `lme4` package the estimated variance is zero but there is variability between the groups.  It is just that this variability does not exceed what would be expected if you had 30 iid normal observations and arbitrarily divided them into 6 groups of 5.  In fact, I expect that those data were simulated in exactly that way.

**Comment by bbolker** [comment]
would it be waffling too much to say  "boundary (singular) fit: see ?isSingular" ?

**Comment by bbolker** [comment]
resolved in 5541fd4e50e03c2f464fab36cab69d138e1b23ec
