### ISSUE TITLE
fail to install: fatal error: RcppEigen.h

### ISSUE THREAD

**Issue by DiogoFerrari** [lme4/lme4#504]
The package fails to install due to error with RcppEigen.h. It has nothing to do with Rstudio, because I don't even use it, as it was suggested in issue #497 already closed. It does not seem to be an issue with RcppEigen either because I have other packages using it.

**Comment by bbolker** [comment]
did you mean issue #479 ? (rather than 497)?

Can you give us more information (`sessionInfo()`, precise error message)?  The most likely answer is that you'll need to re-install the packages Rcpp/RcppEigen before trying to install lme4. The constraints on versions matching properly are much stronger for building or installing a package than for simply running it ...

**Comment by DiogoFerrari** [comment]
Yes, I meant #479. Problem solved after reinstalling RcppEigen. Thanks!
