### ISSUE TITLE
lmer() sometimes doesn't work

### ISSUE THREAD

**Issue by yukitakahashi1** [lme4/lme4#518]
Dear all,
I'm estimating linear mixed-effects model with lmer() for my generated data, but it returns error message:
`Error: number of observations (=200) <= number of random effects (=200) for term (T | id); the random-effects parameters and the residual variance (or scale parameter) are probably unidentifiable`
Also, when I specify group variable larger than individual, it returns the following error:
`boundary (singular) fit: see ?isSingular`
But these work with Stata's `xtmixed`. Are these bug, or some coding error?

MWE:
```
N <- 100;id <- 1:N;id <- c(id,id);gid <- 1:(N/2);
gid <- c(gid,gid,gid,gid);T <- rep(0,N);T = c(T,T+1)
a <- qnorm(runif(N),mean=0,sd=0.005)
gp <- qnorm(runif(N/2),mean=0,sd=0.0005)
u <- qnorm(runif(N*2),mean=0,sd=0.05)
a <- c(a,a);gp = c(gp,gp,gp,gp)
Ylatent <- -0.05*T + a + u
Data <- data.frame(
  Y = ifelse(Ylatent > 0, 1, 0),
  id = id,gid = gid,T = T
)
library(lme4)
library(plm)
fm1 <- lmer(Y ~ T + (T | id), data=Data)
fm2 <- lmer(Y ~ T + (T | gid), data=Data)
pData <- plm::pdata.frame(Data, index = "id") # generate time index automatically - sometimes this helps
fm1p <- lmer(Y ~ T + (T | id), data=pData)
fm2p <- lmer(Y ~ T + (T | gid), data=Data)
```

**Comment by bbolker** [comment]
This is probably more appropriate for the `r-sig-mixed-models@r-project.org` mailing list (follow-ups there, please).

Briefly: `lmer` is complaining because you are trying to estimate 2 random effects per `id`, and there are only two observations per `id`.  `lmer` always includes a residual error term, so the random-effects variances are confounded with the residual variance. A similar example is discussed in more detail [here](https://bbolker.github.io/morelia_2018/notes/mixedlab.html).  You can override the error if you want (see `?lmerControl`); the fixed effects are still estimated reliably, but the random effects variances are underdetermined.

I don't happen to get any singular fit warnings (these are *messages*, not warnings or errors ...) -- that probably depends on the random-number seed.  There is lots of discussion about the meaning of singular fits, e.g. on the [GLMM FAQ](http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#singular-models-random-effect-variances-estimated-as-zero-or-correlations-estimated-as---1)

Followups to r-sig-mixed-models ...
