### ISSUE TITLE
Confusing naming of anova output column when comparing linear mixed models

### ISSUE THREAD

**Issue by vasishth** [lme4/lme4#528]
When we compare two linear mixed models, we get output like the following:

<pre>
  anova(m1,m2)
  ## refitting model(s) with ML (instead of REML)  
  ## Data: dat
  ## Models:
  ## m1: log(rt) ~ cond + ((1 | subj) + (0 + cond | subj)) + ((1 | item) +
  ## m1:     (0 + cond | item))
  ## m2: log(rt) ~ cond + (1 + cond | subj) + (1 + cond | item)
  ##    Df AIC BIC logLik deviance Chisq Chi Df Pr(>Chisq)
  ## m1  7 803 834   -395      789
  ## m2  9 804 843   -393      786  3.54      2       0.17
</pre>

There are two columns called Df, and this is confusing for beginners and possibly also a bit misleading.

The first column from the left that is called Df is referring to the number of parameters, not exactly degrees of freedom as such (if I understand all this correctly). The second-last column from the right has another Df column, which refers to the degrees of freedom of the Chi-sq distribution. 

In classes where I teach linear mixed models, students are already under cognitive overload, and having to deal with such a confusing set of column names seems to bother them. Could this be changed?

**Comment by bbolker** [comment]
A few points (copied from email exchange):

- there is a slight back-compatibility problem; it's conceivable that users were selecting columns based on name (although they would have difficulty selecting a `Df` column!)
- consistency with base R (which isn't very consistent with itself):
     - `anova.lm` uses "Res.Df" for residual df (which lmer doesn't return at all) and "Df"
(for delta-df or "Chi Df"); `anova.glm` uses "Resid. Df" and "Df").

Maybe `Df` -> `Model.Df` ?

**Comment by mmaechler** [comment]
I agree that our column names are really unfortunate .. and had had urges to change them every time I teach (or otherwise try to explain) our anova(.)  output.
I also have not liked  "Chi Df" at all.  We even don't have exact chi^2 distributions, and even less "chi" (without the square) ... *and* the use of  "degrees of freedom" actually is almost always in statistics linked to approximate (or supposedly approximate ..;-) Chi^2 distributions.. so there's really no need for the word "Chi" there.
Here, I think our first "Df" should not be called "Df" at all,  it is just the number of parameters, (or the dimension of the parameter space), and that is (almost?) never called degrees of freedom AFAIK.
(Even the "Total DF" used in old fashion lm ANOVAs is used for a single model anova, and used for the last line as **row** label, and is almost always n-1 (model with intercept),  and rarely n (model w/o int.), 

```r
npar <- function(obj) sum(obj@devcomp$dims[c("p", "nth", "useSc")])
```
would compute this number directly.
Additionally: That column label should rather remain short for printing reasons.
My very first inclination therefore was "#p"  (for "number of parameters"),  but I don't assume you'd like that.

It's very good to consider compatibility with "base R" .. and indeed it's a bit embarassing that `anova.lm` and `anova.glm` are inconsistent.. (and "Resid. Df"  with a space is really nonsense compared to "Res.Df" ... also because of print width waste etc).
But at least it (base) is consistently using "Df"  in all places always meaning the model difference df,


Instead of our  "Df"  and "Chi Df"    I'd strongly prefer something like

"npar"   "Df"

where "npar" could also be "n.par" or "#par"  but  the new "Df" would at least be compatible to all other "Df" in stats' package anova() and many other usages out there.

**Comment by bbolker** [comment]
I'm fine with `npar` and `Df`.  For what it's worth I think `npar` can usually be computed via `nobs(.) - df.residual(.)` (both of those methods are defined for most well-established model classes).

**Comment by bbolker** [comment]
This should be fixed now (and in NEWS).
