### ISSUE TITLE
getData in fortify usage

### ISSUE THREAD

**Issue by wolski** [lme4/lme4#546]
While trying to find a way to extract data from an lmerMod object I noticed that the usage example for the function fortify does not work.

```
(fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy))
fortify(fm1, data = getData(fm1))
```

     Error in getData(fm1) : could not find function "getData"

But which method can I use to get the data from an lmerMod?

**Comment by bbolker** [comment]
Good catch.  At the very least we have to say `data = NULL` since there is no `getData` method. `nlme::getData.lme` could probably be adapted.  However .. can you give more detail about what you're trying to do? `merMod` objects store the model frame, but not the data, so you could use `model.frame(fitted_model)` or `eval(getCall(fitted_model)$data)`.  Neither of these is perfect ...

**Comment by bbolker** [comment]
On closer inspection, we do actually have a `getData` method, it just wasn't exported. Working on updating the NAMESPACE file and documentation.  Should work in development version as of 216edc22c8c , so I'm closing this.  If you have more questions I would suggest `r-sig-mixed-models@r-project.org` as a venue ...
