### ISSUE TITLE
Computing a LMM gives distinct results depending on how the same formula is written

### ISSUE THREAD

**Issue by iago-pssjd** [lme4/lme4#559]
With an example from `lmer` help:
```
data(Orthodont,package="nlme")
Orthodont$nsex <- as.numeric(Orthodont$Sex=="Male")
Orthodont$nsexage <- with(Orthodont, nsex*age)
summary(lmer(distance ~ age + (age|Subject) + (0+nsex|Subject) +
     (0 + nsexage|Subject), data=Orthodont))
```
gives a result, meanwhile, after changing the order of the same terms in the formula,
```
summary(lmer(distance ~ age + (0+nsex|Subject)  + (age|Subject)+
       (0 + nsexage|Subject), data=Orthodont))
```
gives another result.

In this example the difference is minor, but with my working data, with an order the variance of a random effect is 2.181e-04, but after changing the order the variance becomes exactly 0.
In both models I get `convergence code: 0` and also the message `boundary (singular) fit: see ?isSingular` (but for one `isSingular(model)` is `FALSE` and for 0-variance model is `TRUE`)

What does this mean?

Thank you!

**Comment by bbolker** [comment]
It means the *computational* version of the linear algebra is not exactly invariant to changes in the column ordering. (I suspect the precise difference comes in the step where lme4 computes a permutation of the random-effects model matrix that maximizes sparsity.) In general lme4 reorders the model matrix columns based on the number of levels of the grouping factor for each component, but in this case all three components have the *same* grouping factor (Subject), so I believe they'll just be included in the order in which they're given in the formula.

Other comments:

- This is a silly model on statistical grounds (because Sex varies only between subject, not within subject), so the variances for (sex|Subject) and (sex:age|Subject) *should* be zero
- the difference between 2e-4 and 0 doesn't sound large to me (assuming that variance is based on a unitless effect)
- we could try harder to ensure that we estimate variances as exactly zero when they should be (rather than just very small); that's something I worked on a while ago but could revisit.
