### ISSUE TITLE
lmer: Model failed to converge

### ISSUE THREAD

**Issue by tyner** [lme4/lme4#584]
The following code triggers a warning about convergence, whereas nlme::lme handles it just fine.

```r
n <- 2 # number of clusters
N <- 100 # number of observations in each cluster
group <- rep(1:n, each = N)
set.seed(3941)
rndintercept <- rep(rnorm(n), each = N)
outcome <- rnorm(n * N) + rndintercept
mod_lme4 <- lme4::lmer(formula = outcome ~ 1 + (1 | group))
```

**Comment by bbolker** [comment]
This is unfortunate but, I think, pretty much unavoidable.  Increasing the convergence tolerance a little bit *or* changing to one of the optimizers allows it to fit without warnings.  If you check the results you'll see that they're *slightly* worse than the lme fit (about 0.0001 log-likelihood unit difference), with an among-group variance that differs by about 1%.  This seems to be a case where the nloptr implementation of BOBYQA (which we switched to because it seems to be slightly better *most* of the time) does a slightly worse job than the other optimizers.

I realize that this is probably a simplified example, but in general I probably wouldn't recommend fitting mixed models to grouping variables with only two levels ...

This code is not terribly well organized or explained but should give you an idea of what I did to diagnose.

```
m2 <-update(mod_lme4,
       control=lmerControl(optCtrl=list(xtol_abs=1e-12, ftol_abs=1e-12))
       )
aa <- allFit(mod_lme4)
ss <- summary(aa)
ss$msgs
ss$fixef
ss$sdcor
ss$llik-max(ss$llik)
mod_lme <- nlme::lme(outcome ~ 1, random = ~ 1|group)
all.equal(fixef(mod_lme4), fixef(mod_lme))
sqrt(c(unclass(getVarCov(mod_lme))))
```
