### ISSUE TITLE
Error with lmer v1.1-26 with Matrix v1.3.0

### ISSUE THREAD

**Issue by GabrielHoffman** [lme4/lme4#613]
I'm having an issue with lmer v1.1-26 that produces an error with Matrix v1.3.0: 

```r
library(lme4)
#> Loading required package: Matrix

# fit simple linear mixed model
form = extra ~ group + (1|ID)
fit = lmer(form, sleep)

# Use lmerControl() to detect a low rank model
control = lmerControl(check.rankX="stop.deficient" )
fit = lmer(form, sleep, control=control)
#> Warning in qr2rankMatrix(q.r, tol = tol, isBqr = x.dense, do.warn = warn.qr):
#> qr2rankMatrix(.): QR has negative diag(R) entries
#> Error: the fixed-effects model matrix is column rank deficient (rank(X) = 1 < 2 = p);
#> the fixed effects will be jointly unidentifiable
```

This error does not occur with previous version of Matrix.  The issue is fixed in lme4 v1.1-26.9000.  However, this version is not yet on CRAN and I am getting the error in a [Bioconductor package](http://bioconductor.org/checkResults/3.12/bioc-LATEST/variancePartition/malbec1-buildsrc.html) I maintain.  Since the Bioconductor system only loads dependencies from CRAN, I am stuck for the moment.  

Will this fix be pushed to CRAN soon?   

Cheers,
Gabriel

```r
sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin19.5.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lme4_1.1-26  Matrix_1.3-0

loaded via a namespace (and not attached):
 [1] minqa_1.2.4     MASS_7.3-53     compiler_4.0.1  Rcpp_1.0.5     
 [5] splines_4.0.1   nlme_3.1-150    grid_4.0.1      nloptr_1.2.2.2 
 [9] boot_1.3-25     statmod_1.4.35  lattice_0.20-41
```

**Comment by bbolker** [comment]
I believe this is actually due to a bug in `Matrix` 1.3-0; @mmaechler has recently fixed it (as well as making changes in `lme4` that work around it), and according the SVN repository the package is now up to version 1.3-2. I would guess that the new version of `Matrix` will be posted to CRAN soon .... ?  But if not, we could push a new version of `lme4`.

https://r-forge.r-project.org/scm/viewvc.php/pkg/Matrix/?root=matrix

**Comment by mmaechler** [comment]
@bbolker is right on spot. It's embarrassing indeed I put  a thinko  into the `rankMatrix()`  (`method="qr.R"` only) which is used by lme4.  I had hoped the CRAN team would replace Matrix 1.3-0 with 1.3-1 which I sent them on Christmas Eve or so.. but evidently they went into to the Christmas vacation and left that open.  As I got another (much less important) bug report about an old border-line case in Matrix, *and* as I had submitted 1.3-1 to CRAN,  I fixed that bug in yet a new version 1.3-2 .. indeed available from R-forge.  @GabrielHoffman : Could you please try to use that  R-forge version of Matrix and confirm your problem is gone?

**Comment by mmaechler** [comment]
BTW: CRAN vacation is over next Monday (Jan.4).  Both `lme4` or `Matrix`  will not be updated before then.. but I hope and expect Matrix should be updated within a day or two (there are many 100s of reverse dependency checks which CRAN checks too).

**Comment by GabrielHoffman** [comment]
I confirm that `lme4_1.1-26` with `Matrix_1.3-2` works as expected.

Thanks

**Comment by BartJanvanRossum** [comment]
I ran into this same issue with my CRAN package statgenGxE that has `lme4` as a dependency. The issue is fixed with `Matrix_1.3-2`, however since I'm only depending on `Matrix` through `lme4` I cannot change the minimum required version for the `Matrix` package. I was wondering if you would mind updating this in `lme4`?

**Comment by bbolker** [comment]
Hmm. I can update it in `DESCRIPTION`, but (1) it doesn't make sense to do so until the updated `Matrix` is on CRAN; (2) We don't have definite plans for releasing an updated `lme4` on CRAN (although we could if there were demand). (You could also import some function from `Matrix` just so you could add it to `Imports:` with your own desired version dependency ...)

**Comment by BartJanvanRossum** [comment]
I would appreciate if you updated in `DESCRIPTION`, but of course `Matrix` will have to be updated on CRAN first. No need to hurry for me though, I have to update before the end of the week to prevent removal from CRAN, so waiting for dependencies to update first is not really an option. I will just suppress some tests and parts of the vignette.

**Comment by mmaechler** [comment]
As said earlier, do wait on a new Matrix on CRAN "any day now"...
