### ISSUE TITLE
"object is not a matrix" error in `predict()`

### ISSUE THREAD

**Issue by strengejacke** [lme4/lme4#631]
``` r
library(lme4)
data <- read.csv("data_(1).csv")
model <- lmer(response ~ condition_bystanders + (condition_bystanders|ID), 
              data = data)

d <- as.data.frame(expand.grid(unique(data$condition_bystanders), unique(data$ID)))
colnames(d) <- c("condition_bystanders", "ID")
predict(model, newdata = d)
#> Error in model.matrix.default(eval(substitute(~foo, list(foo = x[[2]]))), : object is not a matrix
```

<sup>Created on 2021-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

_Originally posted by @strengejacke in https://github.com/strengejacke/ggeffects/issues/221#issuecomment-861855638_

[data_(1).zip](https://github.com/lme4/lme4/files/6658928/data_.1.zip)

**Comment by bbolker** [comment]
Weird. I assume it has to do with factor/character mismatches, but I'll take a look. Just surprising that we still have errors like this to discover (at a first glance it's not caused by recent changes, but I'll check that too).

**Comment by bbolker** [comment]
Same error occurs for 1.1-26 and 1.1-25, and with `options(stringsAsFactors = TRUE)` set ... ???

**Comment by strengejacke** [comment]
But this is not related to the discussion at https://github.com/glmmTMB/glmmTMB/issues/602? I know it's a different issue in glmmTMB, but you mentioned the code that checked factor levels/order here: https://github.com/glmmTMB/glmmTMB/issues/602#issuecomment-651194250

**Comment by bbolker** [comment]
Don't know, I will check. Same error if I use `d2 <- as.data.frame(lapply(d, as.character))` as `newdata` (so we shouldn't have a problem with factor levels ??)

**Comment by bbolker** [comment]
This seems bizarre.  All I can see so far is that at some point one of the factor gets a contrast attribute that is a `Matrix` rather than a `matrix` - I think that's probably the problem, but I don't yet know where/why it's happening.

**Comment by bbolker** [comment]
Only happens if the number of levels of the grouping variable is > 100

Problem has to do with [this](https://github.com/lme4/lme4/blob/67afecbff4831de9caf6b5891e8f307a01f7197e/R/predict.R#L159), [this](https://github.com/lme4/lme4/blob/67afecbff4831de9caf6b5891e8f307a01f7197e/R/predict.R#L194-L195).

Git blame says this has something to do with @mmaechler (from [this commit](https://github.com/lme4/lme4/commit/9a3cbe153f8fb26ac5282e16c55fde71c8574611), but I'm trying to figure out why it's never bitten us before?  I might try some archaeology with older versions of the `Matrix` package ...

```r
library(lme4)
packageVersion("lme4")
data <- read.csv("data_(1).csv")

## WORKS
dataX <- data
set.seed(101)
dataX$ID <- sample(unique(dataX$ID)[1:99], size = nrow(dataX),
                   replace=TRUE)
model <- lmer(response ~ condition_bystanders + (condition_bystanders|ID),
              data = dataX)
d3 <- with(dataX,
           expand.grid(condition_bystanders = unique(condition_bystanders),
                              ID = unique(ID)))
predict(model, newdata=d3)

## FAILS
dataY <- data
dataY$ID <- sample(unique(data$ID)[1:101], size = nrow(dataX),
                   replace=TRUE)
d4 <- with(dataY,
           expand.grid(condition_bystanders = unique(condition_bystanders),
                              ID = unique(ID)))
model2 <- update(model, data= dataY)
predict(model2, newdata=d4)
```

**Comment by bbolker** [comment]
Trying with Matrix 1.2-18 (2019-11-27) : nope, fails with old Matrix too.  Maybe no-one tries to make predictions on new data when they have lots of levels in their grouping variable ???

**Comment by bbolker** [comment]
```r
remotes::install_github("lme4/lme4", ref= "a25e6f4c26e99") ## May 22 2018: works
remotes::install_github("lme4/lme4", ref= "9a3cbe153f") ## hmm, also works
```

Time to try git bisect?

```r
git bisect start
git bisect bad                 # Current version is bad
git bisect good a25e6f4c26e9    # good
. ./runtest
git bisect good 
./runtest ## 91407d0187
git bisect bad
. ./runtest ## 98b9f5a578
git bisect good
. ./runtest ## b3a627ef9cc
git bisect good
. ./runtest ## 1ee8c8ebaf0
git bisect bad
. ./runtest ## f426fa2bb3df
git bisect bad
. ./runtest ## 9d45027b8d
git bisect bad
. ./runtest ## f8b6ef57d9
git bisect bad
```

So the culprit seems to be f8b6ef57d95 (Aug 20, 2020). Discussed [here](https://github.com/lme4/lme4/issues/467) I guess that's what we get for accepting pull requests!  At least we know where the problem is, but it will take more brain than I have right now to see exactly what the problem is & fix it.





```

---

**Comment by bbolker** [comment]
Hmm. I really appreciate the PR, but ... I don't fully understand what all the machinery is supposed to do, and I wonder whether your patch is somehow undoing the intention of the original code? That is, will it end up converting some contrast matrix from sparse to dense and blowing up memory **in some situation where this isn't necessary to complete the task**?

If you know the answer, that's great. Otherwise someone (me or ??) will have to review the logic according to which the sparse matrices are being used in the first place, and figure out why it breaks when we try to predict with new data, and whether it's possible to un-break it *without* losing sparsity ...

**Comment by mmaechler** [comment]
Hmm, from here too:  It's actually great to use sparse contrast matrices  in such cases...  one of the few things you can even do in base R without explicitly loading `Matrix`:

`model.matrix(.....,  sparse=TRUE)`

*and* our code in many other places works very well with sparse matrices.

**Comment by bbolker** [comment]
@mmaechler, I have some questions/comments ...

1. As far as I can tell `model.matrix(..., sparse = TRUE)` doesn't actually do anything (other than get swallowed by `...`)

```r
m <- methods("model.matrix")
setNames(lapply(m, function(x) names(formals(get(x)))), m)
## $model.matrix.default
## [1] "object"        "data"          "contrasts.arg" "xlev"     "..."          
## $model.matrix.lm
## [1] "object" "..."   
```

Maybe you meant `sparse.model.matrix()` ?

2. `model.matrix()` doesn't accept sparse matrices as part of `contrasts.arg`, but `sparse.model.matrix` does.

```r
## setup
dd <- data.frame(f=factor(1:3))

## fails  with "object is not a matrix"
model.matrix(~f, data=dd,
             contrasts.arg = list(f=contr.treatment(3, sparse=TRUE)))
## add sparse=TRUE as an arg to model.matrix(): same failure
model.matrix(~f, data=dd,
             contrasts.arg = list(f=contr.treatment(3, sparse=TRUE)),
             sparse = TRUE)

## add sparse=TRUE (ignored!)
model.matrix(~f, data=dd, sparse = TRUE)


## all three of these work and create sparse matrices, although looking at the code of
## `sparse.model.matrix`, both versions 2 and 3 would first create a *dense* contrast matrix ...
## constructs a *dense* contrast matrix ... don't know what happens in general
Matrix::sparse.model.matrix(~f, data=dd,
                    contrasts.arg = list(f=contr.treatment(3, sparse=TRUE)))
Matrix::sparse.model.matrix(~f, data=dd)
Matrix::sparse.model.matrix(~f, data=dd, contrasts=contr.treatment(3))
```

I will see if we can adjust the code to use `sparse.model.matrix()` iff `sparse=TRUE` in the predict step ...

**Comment by bbolker** [comment]
@strengejacke , @bwiernik please test?

**Comment by strengejacke** [comment]
At least for the initial example, it now works fine!

**Comment by bwiernik** [comment]
Seems to be working, yes. Thanks!

**Comment by mmaechler** [comment]
@bbolker : yes, I'm sorry, I've confused  `model.matrix` with another base function that uses `Matrix`-sparseMatrices:
`contrasts()` (and `xtabs()`).
