### ISSUE TITLE
Issue with boundary (singular) fit: see ?isSingular

### ISSUE THREAD

**Issue by sashavas3** [lme4/lme4#644]
Hi,

I'm running a piecewise SEM with 3 component models:

lmer(response variable1 ~ predictors + (1|Point) + (1|Year), input_table)

glmer(response variable2 ~ predictors + (1| Point) + (1|Year), family = "binomial", input_table)

glmer(response variable3 ~ predictors + (1| Point) + (1|Year), family = "binomial", input_table)

Because sampling involved visiting 18 points in spring of 2018 and again in spring of 2019, I specified samping point and year as random effects.

When I run the model, this warning message appears:
Check model convergence: log-likelihood estimates lead to negative Chi-squared!

This message also appears:
boundary (singular) fit: see ?isSingular

From what I've read about the second message, it could be due to random effect variance estimates of zero. I checked and this happens in the 1st and 3rd component models. In the 1st model "Point" has zero variance, and in the 3rd model "Year" has zero variance.

My first question is (and I apologize in advance if this is silly to ask) whether this means that there's not really an effect coming from Point in component model 1 and from Year in component model 2? If so, would it be possible to remove those random effects to end up with:

lmer(Response variable1 ~ Predictors + (1|Year), input_table)

glmer(Response variable2 ~Predictors + (1| Point) + (1|Year), family = "binomial", input_table)

glmer(Response variable3 ~ Predictors + (1| Point), family = "binomial", input_table)

My second question is whether the warning "Check model convergence: log-likelihood estimates lead to negative Chi-squared!" is related to these singularity issues?

Thanks!

**Comment by bbolker** [comment]
Can you please ask this on `r-sig-mixed-models@r-project.org` (subscribe first, the subscription page is googleable)? See https://github.com/lme4/lme4/blob/master/README.md#where-to-get-help

This warning message is new to me, I've never seen it before/am 99.9% sure it's not coming from `lme4`. I can't find it in the code base for `piecewiseSEM` either ... which package(s) are you using?

**Comment by sinushelf** [comment]
Hi,
I have kind of the same problem. I run also a piecewise SEM. The warning message "boundary (singular) fit: see ?isSingular" appeared also with this data but not in the model below. I use the package piecewiseSEM.

  lmer(variable1 ~  variable2   + (1 | location), data)
  lm(variable2~ variable3, data)
Because I had 18 different locations with 2 or 4 samples each, I specified location as random effect.

In this model the warning message "Check model convergence: log-likelihood estimates lead to negative Chi-squared!" appeared. And I get "Chi-Squared = NA with P-value = NA and on 1 degrees of freedom". How can I handle this?

Thanks!
