### ISSUE TITLE
Sign error in unexported function `gradient`

### ISSUE THREAD

**Issue by jaganmn** [lme4/lme4#652]
I noticed this a while ago and forgot to report... `R/deriv.R`, which has not really been touched since its creation in 2013, has

https://github.com/lme4/lme4/blob/1fbf0afea36782cca7c58e3d5338ea88eebf4b9c/R/deriv.R#L39-L56

where it seems clear that `xsub[i] <- x[i] + ldelta` should be `xsub[i] <- x[i] - ldelta`. 

AFAICT, the only function in `R/deriv.R` that is used anywhere in `lme4` is `deriv12` (once in `R/lmer.R`), and there is a comment at the top of the file saying as much. Perhaps the unused functions can be deleted? Or at least wrapped in `if (FALSE) {}` so that they don't pollute the namespace?

**Comment by mmaechler** [comment]
I've started  to fix this (removing all but `deriv12()` which is called from `lmer.R`'s  `optwrap()`
*and* started to carefully read `deriv12()`  to see if their might be a similar  cut'n'paste thinko...  and there *is*:
 in  https://github.com/lme4/lme4/blob/master/R/deriv.R#L95-L102  first deal with upper, then with lower bounds, and in the 2nd part,  line 100 has `xadd`  but obviously should have `xsub` : 
```
lbActive <- !is.na(lower) & xadd<lower
```
.. now that means this has been wrong all the time ... but the good news is that this has not had any effect, because we have used `deriv12()` only with its default  `lower` and `upper` bounds, set to all `NA`, i.e., no bounds. 
I will commit a change which should be a bit *faster* in this case.

**Comment by mmaechler** [comment]
Now committed:  68cbd54f457137250a95fbfe44480bab99b9d840

**Comment by bbolker** [comment]
yikes.  Thanks!
