### ISSUE TITLE
Removing sensitive data from S4 object of class glmerMod

### ISSUE THREAD

**Issue by AnnaCalderon** [lme4/lme4#657]
Hi, 
My team (@RaymondBalise, @gabrielodom) and I created the following  S4 object of class glmerMod.

`model_a <- glmer(y ~ x1 + x2+ x3 + 
               x4 + (1|group), family = "binomial", data = dat)`

The data set used to create this model contains sensitive information, which cannot go public in any form. However, the prediction model will become public for predictions using user input. Therefore, I have inspected the model's slots one by one, and I have found and deleted subsets of the data. For example, in slots frame and flist. 

I'm hoping to get guidance either a more effective and efficient way to do this or how to ensure that there are no more pieces of sensitive data in the model object. 

Thank you!
Anna

**Comment by bbolker** [comment]
It depends a little bit on how paranoid you are about information leakage.

The `resp` component will give information about the predicted mean for each observation in the original data set, as well as the number of observations (but no direct information about the covariates).

You do need to get rid of `@pp`, because it contains the fixed-effect model frame (`$X`) internally.

Honestly, I think the safest thing to do would be to save the formula and the fixed-effect coefficients and write your own prediction function, e.g.

```r
safe_info <- function(m) {
   ret <- list(beta = getME(m, "beta"),
        form = formula(m, fixed.only = TRUE),
        family = family(m))
   environment(ret$form) <- emptyenv()
   return(ret)
}
mypred <- function(s, newdata, type = "response") {
    newX <- model.matrix(s$form, data = newdata)
    eta <- newX %*% s$beta
    if (type != "response") return(eta) else return(s$family$linkinv(eta))
}
```
This assumes a bunch of things:

- you're making predictions on the fixed effects only (if you want to include the random effects, you need to know the factor levels of the original RE variables, and do something sensible with new factor levels)
- you aren't worried about people providing new data where the factor levels are in a different order from the original data set
- the original model didn't have any terms with data-dependent bases (`poly()`, `splines::ns()`, etc.)

I'm sorry this is so complicated, but it is ...

**Comment by RaymondBalise** [comment]
Hello Ben,
Thank you for the advice/help.  We are building prediction models for relapse for people who are getting treatment for substance use. So, the data are **_extremely_** sensitive.  Our goal is to make predictions for new people using a shiny web app.  So, we can control the input values and factor levels.  Our data have patients who are in 12 different treatment sites (clinics).  So we are thinking we will provide a range of prediction intervals (and try to convert the intervals into a density).  We just dug out the equations for the point estimates and CLs on logistic mixed model....  this will be an adventure. :)

**Comment by bbolker** [comment]
Sorry, this slipped through the cracks.  To be precise, you want to make predictions for individuals given a set of fixed-effect covariates and specify a clinic as well?  There are a few pieces here:

- prediction of the mean values seems fairly straightforward 
    - on the link scale you basically just need `X %*% beta + b(i)`, where `b(i)` is the value for the ith group: `getME(fitted_model, "b")` and `getME(fitted_model, "beta")` will get you b and beta respectively, the `X` is your vector of predictors.
    - then you need to transform back to the probability scale

This is basically just the same as the machinery I gave above, except that you would need to extract `b` as well in `safe_info` and include it in `mypred`.

To be honest, incorporating bias correction (i.e. back-transforming the mean on the logit scale won't give you the mean on the probability scale) and accounting for the uncertainty of `b` are both a little tricky - neither of them is actually done in the current `lme4` predict methods. There are a variety of ways of attacking these problems ...

Suppose we had fake data like this:

```r
library(lme4)
set.seed(101)
n <- 1000
nc <- 10
dd <- data.frame(x1 = rnorm(n), x2 = rnorm(n), x3 = rnorm(n), x4 = rnorm(n), c = factor(rep(1:nc, n/nc)))
dd$y <- simulate(~x1+x2+x3+x4+(1|c), family = binomial,
    newdata = dd,
   weights = rep(1,n),
   newparams = list(beta = rep(1,5),  ## intercept plus 4 fixed effects
                               theta = 1)            ## sd of RE
)
```

Could you suggest values for `beta`, `theta`, `n` that would be ballpark-realistic for your situation?

**Comment by RaymondBalise** [comment]
Thank you for the support Ben!  We think we came up with a solution yesterday.  One of the programmers on our team is going to try to build a lookup table using the bootstrap estimates she used to make our predictions (our predictors are binary or ordinal so this is not insane computationally).  I will send up another flare if we run into problems.

**Comment by bbolker** [comment]
OK, going to close this then. Feel free to re-open.
