### ISSUE TITLE
Faster refit() for recycling models across many responses?

### ISSUE THREAD

**Issue by GabrielHoffman** [lme4/lme4#678]
Hi @bbolker, 
I wrote the `variancePartition` package we corresponded about a few weeks ago.  The package is designed for gene expression datasets where the formula of the linear mixed model is constant, but the model is fit for each of ~20k genes.  I've done a lot of work parallelizing across genes, but with large datasets its can still take a while to run.  

One way to improve performance is to recycle parts of an initial model fit, since the formula is the same for all genes.  Using `refit()` in the trivial example below gets only a ~2x speedup, so it seems like a faster version should be possible:

```r
library(lme4)
#> Loading required package: Matrix

# load dataset
data("sleepstudy", package="lme4")

# fit model
fit = lmer(Reaction ~ Days + (1 | Subject), sleepstudy)

# time fitting model 1000 times
system.time(replicate(1000, lmer(Reaction ~ Days + (1 | Subject), sleepstudy)))
#>    user  system elapsed 
#>  13.450   0.361  13.911

# time refit'ing model 1000 times
# Note that response is actually the same here, so the speed up could be much larger
system.time(replicate(1000, refit(fit, newresp=sleepstudy$Reaction)))
#>    user  system elapsed 
#>   7.554   0.260   7.858
```

Are you interested in this problem? I image other people want to fit models across many responses too.

Specific needs:
1) faster version of `refit()` 
2) enable `refit()` to update the weights as well as response

I'm happy to contribute to this. I took a shot, but the `refit()` code is pretty complicated.

Cheers,
Gabriel

**Comment by bbolker** [comment]
Hmmm.  I'm willing to participate in this but don't think I have the time and energy to drive the project. 

- It's not immediately obvious to me how to speed up `refit()`, although I suspect that part of the problem in this case is that the problem is **too small** to benefit a great deal from the tricks that are used by `refit`. Could try some profiling. (I guess your point is that using exactly the same response means that we shouldn't have to do very much optimization? Part of the problem here is that the optimization machinery is going to be re-initialized; given that the first few steps of the optimization are effective, most of the time will be taken in 'polishing' ...)  How big are your individual data sets?
- I think allowing for updating the weights should be relatively easy.

```r
library(rbenchmark)
benchmark(fit = lmer(Reaction ~ Days + (1 | Subject), sleepstudy),
                   refit = refit(fit, newresp=sleepstudy$Reaction),
            replications = 500)

   test replications elapsed relative user.self sys.self
1   fit          500  12.474    1.309    11.463    1.436
2 refit          500   9.526    1.000     8.870    0.980
```

Turning off the gradient-checking machinery run after the model fit helps a tiny bit, but not as much as I hoped:

```r
cc <- lmerControl(calc.derivs=FALSE)
fit2 <- update(fit, control =cc)
benchmark(fit = lmer(Reaction ~ Days + (1 | Subject), sleepstudy, control = cc),
                   refit = refit(fit2, newresp=sleepstudy$Reaction),
            replications = 500)
   test replications elapsed relative user.self sys.self 
1   fit          500  11.459    1.317    10.559    1.341    
2 refit          500   8.700    1.000     8.072    0.934 
```

**Comment by GabrielHoffman** [comment]
Hi @bbolker,
I'm getting back to this after a very long time.  

Do you think it would be feasible to allow updating weights in `refit()`?

Gabriel

**Comment by bbolker** [comment]
Does this do what you need?

```r
remotes::install_github("lme4/lme4@refit_weights")
library(lme4)
fm1 <- lmer(Reaction ~ Days + (1|Subject), sleepstudy)
w2 <- rep(2, nrow(sleepstudy))
fm2 <- update(fm1, weights = w2)
fm3 <- refit(fm1, newweights = w2)
sigma(fm1) ## 30.99
sigma(fm2) ## 43.82
sigma(fm3) ## 43.8153 (uses est params as starting points)
sigma(refit(fm2)) ## same as previous
```

**Comment by bbolker** [comment]
Case 1 tickled a LONG-standing bug in `refit`. From [here])(https://github.com/lme4/lme4/blob/771498cbdbae6dcb46c337f779f2208e78a2cf9d/R/modular.R#L535-L537):

> FIXME / note: REML does double duty as rank of X and a flag for using REML maybe this should be mentioned in the help file for mkRespMod??  currently that help file says REML is logical.

`refit` was previously passing `REML = if(isREML(object))`, is now passing `REML = object@resp$REML`

**Comment by GabrielHoffman** [comment]
Thanks.  I am working on a major refactor of my `variancePartition` Bioconductor package that will include using this new version of `refit()`.  I'll do some extensive testing comparing my old and new versions, and I'll let you know if I have any issues with `refit()`.

As far as speeding up `refit()`, I'll take a look at its performance on real data and take a shot at profiling.

**Comment by bbolker** [comment]
Ugh, this is a bit tricky.

The problem is that (unlike the response variable, which is stored internally in the model frame) the weights only live in the environment of the formula, which in this case **is the global environment**.  

According to the code snippet you cited, `lmerTest` tries to evaluate the call in:

- the parent frame
- `sys.frames()[[1]]`
- the environment of the formula (the same as the global environment, in this case)
- the environment of the model (NULL, in this case)

The only place `w` exists is in the global environment, which is the same as the environment of the formula (it hasn't been copied). So when you remove `w` from the global environment, you're also removing it from the environment of the formula/model (these are all synonymous in this case).

I'll try to think of some workarounds; it's also possible that `lme4` is not being quite as careful as it could be about where the weights component of the call is being looked for ...

**Comment by GabrielHoffman** [comment]
Of course my example of deleting the weights variable isn't realistic.  But it's similar to the case where the weights vector is no longer in scope.  Here is a more realistic example: 

```r
library(lme4)

# initial fit
fit.init = lmer(Reaction ~ Days + (1|Subject), sleepstudy)

# use refit with new weights, then summarize the fit
run_refit = function(data, fit.init.local){
	w = 1:nrow(data)
	fit = refit(fit.init.local, newweights = w)
	processed_fit(fit)
}

# apply some post-processing
processed_fit = function(fit){
	lmerTest:::as_lmerModLmerTest(fit)
}

run_refit( sleepstudy, fit.init)
# Error in lmerTest:::as_lmerModLmerTest(fit) : 
#  Unable to extract deviance function from model fit
```

**Comment by bbolker** [comment]
There's a fairly straightforward workaround, which I will work on implementing internally:

```r
run_refit <- function(data, fit.init.local){
	w <- 1:nrow(data)
	fit <- refit(fit.init.local, newweights = w)
        assign("w", w, environment(formula(fit)))
	processed_fit(fit)
}
```

**Comment by GabrielHoffman** [comment]
Thanks for the fix.  Can you push it to CRAN?

**Comment by bbolker** [comment]
Working on it.

**Comment by bbolker** [comment]
On CRAN now (source; Win and MacOS binaries will take longer to rebuild)
