### ISSUE TITLE
allFit maxfun

### ISSUE THREAD

**Issue by AnnePdM** [lme4/lme4#685]
I have fitted a binary response multilevel model with random intercepts only. Initially I used the default `glmer` controls. Then I used `allFit` to compare the optimizers. I also wanted to use `maxfun` to change the maximum number of function evaluations to see how this affected the fit of the model (my model wasn't, and still isn't, converging). My problem is that when I compared the output from `allFit`, I noticed that it was only `bobyqa` that was affected by the change in `maxfun`. As `maxfun` is an argument for `allFit`, I assumed that it would work for all optimizers. Is my assumption wrong?
![image](https://user-images.githubusercontent.com/12153921/172593055-44709eec-0411-413e-b88b-f5fdc76bc428.png)

**Comment by bbolker** [comment]
This is a good point.  This is a little bit of a mess, since each optimizer has a *different* parameter for specifying the maximum number of iterations of the algorithm and/or function evaluations (usually not the same). This certainly seems like a bug.  On the other hand, if the plot you're showing here actually represents your results, I'm not sure I would worry about it very much since the log-likelihood only changes by a tiny amount (about 0.05 log-likelihood units). 

However, (a) I realize you may be showing me only a part of a larger workflow, where these differences would really matter, and (b) the function should really work as advertised/document what it does.  I can probably hack `allFit` to make it translate `maxfun` appropriately across optimizers (in the internal `mkOptCtrl` function).

Other than curiosity, can you say how important this bug fix is to your workflow ... ?

**Comment by AnnePdM** [comment]
This is indeed only a small part of my workflow and, notwithstanding the small changes in log-liklihood, I still get a message that the model has not converged. I was using `allFit` to provide a better understanding of the optimisers and iterations because, beyond my proof-of-concept, I will need to fit the same model to a large number of datasets each with around 40,000 observations. This is likely to be a lengthy process so I wanted to do some testing before I started. 

It is not essential to my work that the bug is fixed but it is essential that I know what to expect of the package. This leads me to another question. I understand that `allFit` uses the `update` function. Does this mean that the elapsed time that emerges from `allFit` will not represent the elapsed time of original model fit (given the same optimising parameters)? If so, can I assume that the relative elapsed times between the (in my case) four optimisers will give me some idea of which optimiser is fastest? In the project I describe, I will have to make a compromise between speed and accuracy.

Many thanks for your help.

**Comment by bbolker** [comment]
one quick answer: in the current version, `update` is no faster than running the commands from scratch - all it does is grab the `call` component of the object, make some substitutions, and re-evaluate it ...
