### ISSUE TITLE
stop if multiple response vars on LHS of formula

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#733]
What does this do/why doesn't it throw an error ... ?

```r
mm <- mtcars |> transform(cyl = factor(cyl))
lmer(mpg + disp ~ hp + (1|cyl), mm)
Linear mixed model fit by REML ['lmerMod']
Formula: mpg + disp ~ hp + (1 | cyl)
   Data: mm
REML criterion at convergence: 343.0941
Random effects:
 Groups   Name        Std.Dev.
 cyl      (Intercept) 111.42  
 Residual              51.11  
Number of obs: 32, groups:  cyl, 3
Fixed Effects:
(Intercept)           hp  
   212.7046       0.1588  
```

**Comment by m-clark** [comment]
Caught my curiosity. Looks like it just performs the LHS operation (in this case, adds them) to produce an outcome.

``` r
library(tidyverse)
library(lme4)
#> Loading required package: Matrix
#> 
#> Attaching package: 'Matrix'
#> The following objects are masked from 'package:tidyr':
#> 
#>     expand, pack, unpack

mm <- mtcars %>% 
  mutate(
    cyl = factor(cyl),
    mpgdisp = mpg + disp
  )

m1 = lmer(mpg + disp ~ hp + (1|cyl), mm)
m2 = lmer(mpgdisp ~ hp + (1|cyl), mm)

identical(coef(m1), coef(m2))
#> [1] TRUE
identical(VarCorr(m1), VarCorr(m2))
#> [1] TRUE
```

**Comment by bbolker** [comment]
The main thing I can't believe is that (AFAIR) this has never come up before ...

**Comment by dushoff** [comment]
Not _that_ unlikely, since I seem to remember that's how we saw it in the wild.

**Comment by bbolker** [comment]
My last sentence was meant to suggest that someone might *intend* to make the response variable equal the sum of several different variables in their data set, i.e. a real use case (e.g. a reason we might want to make this a warning instead of an error ... ?  Although it's hard to imagine a case where (1) someone would want to add variables to create a response variable and (2) it would be very inconvenient to do this in an upstream step rather than as part of the formula ...)

Again, as comparison, this has never been disallowed by `lm()` (even though there `cbind(x,y,z)` *is* allowed as a response variable, and it would be easy to thing that a multivariate response should be specified as `x+y+z` instead). (I'm guessing that the response from R-core about this would be the equivalent of the punchline from the joke: "Doctor, it hurts when I do this". "Well, then, don't do that.")

**Comment by mmaechler** [comment]
As you say, it may not be a good "strategy" to do,  but there will  be cases where it's more natural to do than to create a new y-variable explicitly.  Further note that it *does* make the call listed in `summary(.)`  more readable {no new variable names to remember}.  ==> Yes, as R-core member, I strongly think it should not be discouraged,  as it works "correctly".
e.g. consider
```r
summary(lm( mpg/wt ~ hp + cyl, data=mtcars) )
```
and many other functions/arithmetic on the LHS  conceptually make sense   and if you try out quite a few of these,
it's easier to keep track with the correct formula  rather than by defining new variables for all of these.

I really don't see a reason for change, warning, ...

**Comment by bbolker** [comment]
I was going to special-case `+` detection for a warning (I myself have used the division-on-the-left-side idiom ...) but I'm convinced.
