### ISSUE TITLE
weights argument only takes variables that are defined in the global environment

### ISSUE THREAD

**Issue by AmeliaES** [lme4/lme4#742]
Many thanks for creating lme4 which is a fantastic package.

I noticed the weights argument only takes variables that are defined in the global environment and thought it might be useful to share this with you. Apologies if this is addressed in a previous issue, I couldn't see anything that was highlighting exactly this though.

This problem only came to light as I was using lmer in a Shiny app and wanted to allow users the option to give a character string of their weights column that could be parsed to the weights argument in lmer. I've reproduced the same error I was getting using a function (instead of Shiny environement) as an example.

Many thanks again.

```
`# ----------------------------------
# Read in data and make a weights column (as was done here: https://github.com/marjoleinF/misc/blob/master/weights_and_offset_bug_report_lme4.md#lmer-creates-weights-and-offset-variables-in-global-environment)

library(lme4)
library(dplyr)
data("sleepstudy", package = "lme4")
sleepstudy$wght <- rep_len(1:2, length.out = nrow(sleepstudy))


# ----------------------------------
# The following works fine:
lmer(formula = "Reaction ~ Days + (Days | Subject)",
     data = sleepstudy,
     weights =  wght)


# This also works:
WeightVariableName <- "wght"
lmer(formula = "Reaction ~ Days + (Days | Subject)",
     data = sleepstudy,
     weights =  sleepstudy[[WeightVariableName]])

# This works too:
weightsVec <- pull(sleepstudy, !!sym(WeightVariableName))
lmer(formula = "Reaction ~ Days + (Days | Subject)",
     data = sleepstudy,
     weights =  weightsVec)

# ----------------------------------
# However, this does not work because "weightsVecInFunc" is not defined in the global environment:

testlmer1 <- function(weightsTest){

  weightsVecInFunc <- pull(sleepstudy, !!sym(weightsTest))

  fit <- lmer(formula = "Reaction ~ Days + (Days | Subject)",
              data = sleepstudy,
              weights =  weightsVecInFunc)
  return(fit)
}

testlmer1(weightsTest = "wght")
# Error in eval(extras, data, env) : object 'weightsVec' not found

# This doesn't work for the same reason:
testlmer2 <- function(weightsTest){

  fit <- lmer(formula = "Reaction ~ Days + (Days | Subject)",
              data = sleepstudy,
              weights =  sleepstudy[[weightsTest]])
  return(fit)

}

testlmer2(weightsTest = "wght")
# Error in (function(x, i, exact) if (is.matrix(i)) as.matrix(x)[[i]] else .subset2(x, : object 'weightsTest' not found
```

**Comment by bbolker** [comment]
I will look into this, but the general rule is that `lme4` looks for variables in the data frame and in the *environment of the formula*. We try to handle other cases too, but handling all of the possible permutations of scoping is hard ...

It also helps a lot to pass the formula *as a formula* rather than as a character string that gets converted to a formula later, for example this works:

```r
testlmer1 <- function(weightsTest){
    weightsVecInFunc <- pull(sleepstudy, !!sym(weightsTest))
   fit <- lmer(formula = Reaction ~ Days + (Days | Subject),
              data = sleepstudy,
              weights =  weightsVecInFunc)
  return(fit)
}
testlmer1(weightsTest = "wght")
```

If you really need your example to work as is I can try to dig in and see what would be necessary, but if the workaround is OK for you then I will close this as an unhandled edge case ...

**Comment by bbolker** [comment]
PS: unless you're attached to the tidyverse, I would say that `sleepstudy[[weightsTest]]` is more transparent than `pull(sleepstudy, !!sym(weightsTest))` ...

**Comment by bbolker** [comment]
I will probably close this soon unless I hear otherwise (i.e., that the workaround doesn't work for you.  More specifically, the documentation (`?lme4` , description of `data` argument) does say

> If `data` is omitted, variables will be taken from the environment of `formula` (if specified as a formula) or from the parent frame (if specified as a character vector).

This could be amplified by saying (something like)

> If `data` is omitted (or variables, including offset and weights variables, are not included in `data`), variables will be searched for in the ...

I could spend a little more time investigating/explaining *exactly* what goes wrong in this case, and/or adding an example in the help page showing something like this ...

**Comment by AmeliaES** [comment]
Thanks very much for the detailed reply. I'll pass the formula as a formula and use `sleepstudy[[weightsTest]]` instead of tidyverse. Many thanks for your time looking into this.
