### ISSUE TITLE
Processing of secondary variables

### ISSUE THREAD

**Issue by user1212dasdas** [lme4/lme4#751]
Under the HLM framework, my first-level variables are individual survey data, and the second-level variables are economic indicators of a region. This may be the same for all individuals in the same region. In this case, can lme4 be used to analyze mixed effects? ? Or are there any specific requirements for secondary variables?

**Comment by user1212dasdas** [comment]
Specifically, there are ten secondary variables, and individuals in each region have the same secondary variables (economic indicators). This seems to be the same as having only one grouping factor. There is not much difference. It will only cause serious collinearity and difficulty in model fitting.

**Comment by bbolker** [comment]
Can you be slightly more specific about the model you're fitting? (For brevity, you can consider a single predictor at each level.) For example, suppose you try to fit the model

```
y ~ 1 + level1 + level2 + (1 + level1 | region)
```

Where `level1`, `level2` are the predictor(s) at each level. You can't fit a random effect for the variation of the effects of `level2` across region (this effect is unidentifiable because as you state there is no variation in the value of `level2` within regions), but as long as you don't try to do that everything should be OK.

I'm going to close this, as it's more suited to Cross Validated or the `r-sig-mixed-models@r-project.org` mailing list (see https://github.com/lme4/lme4/blob/master/README.md#where-to-get-help ), but feel free to follow up in either of those venues.
