### ISSUE TITLE
Mixed models biased towards small clusters and not respecting partial pooling

### ISSUE THREAD

**Issue by IlmariTamminen** [lme4/lme4#752]
Hi. I hope I have understood something fundamental wrong, please correct me if so. [Here](https://stats.stackexchange.com/questions/630190/mixed-models-of-lme4-and-nlme-in-r-not-respecting-rules-of-partial-pooling) you can find detailed background and demonstrations of the lme4-fitted mixed models which I believe do not respect the mathematical rules of the partial pooling.

**Comment by bbolker** [comment]
Hi, I appreciate the question, but it will take some time and effort to dig into it. Cross Validated is the correct venue for the question (see [here](https://github.com/lme4/lme4/blob/master/README.md#where-to-get-help). The one thing I'll say here is that `lme4`, `nlme`, `glmmTMB`, and many other implementations of mixed models give similar (sometimes identical up to expected floating-point noise) results, so my prior probability that there's something you're not understanding, rather than a bug or a fundamental mistake in the software. However, it seems like a carefully framed question, and the issues may indeed be subtle ...

**Comment by IlmariTamminen** [comment]
Thanks @bbolker ! I got afraid that the question becomes buried and forgotten, and I am still unsure where the problem is actually. The working order sounds great. On the Cross Validated, let's continue figuring out have I done something wrong. Then I will post the conclusions here, if the approach is okay.

**Comment by IlmariTamminen** [comment]
I close the issue. The model fitting seems to be reasonable, but the topic and literature are complex causing confusion about the very motives of and how the mixed models should actually work in detailed level. I also made a mistake adding further confusion. More information available in the answers of the above-mentioned discussion. Maybe the most important take-home message here is, that the mixed models try to manage cluster outliers, I gave too much attention for the partial pooling of smaller clusters.
