### ISSUE TITLE
Posit Cloud R - Error in initializePtr() :    function 'cholmod_factor_ldetA' not provided by package 'Matrix'

### ISSUE THREAD

**Issue by JoeAM11** [lme4/lme4#759]
Hello! 
I am new to linear mixed effects models and I am currently learning to used the with some tutorials (https://www.hiercourse.com/docs/00_SolutionsExercises_mixed.pdf)

I am running in **Posit Cloud** and have some problems while running the following command: 

`
pref_m1 <- lmer(LMA ~ species + dfromtop + species:dfromtop + (1|ID), data=arbol)
`

The error is as folllows:
![image](https://github.com/lme4/lme4/assets/113150506/da6190f9-21d2-4cd5-851e-a0083b71b219)

I can't seem to solve it. I have uninstalled and installed packages but haven't been able to solve it. What do you suggest I can do? Thank you!

**Comment by joshqsumner** [comment]
I have started getting the same error the last two days in github actions for windows and ubuntu using release R version. Checks were passing November 8th, 2023 and are failing November 10th, 2023 with no changes to the code/package being checked. I checked the [Matrix package's news](https://cran.r-project.org/web/packages/Matrix/news.html) since the timing corresponds to the new version there and nothing immediately jumped out at me (but I am not sure I would notice the relevant change since the [history of the namespace](https://github.com/cran/Matrix/commits/323f4d9b0722ba6f61682874a8d92ebdbf93d8fa/NAMESPACE) doesn't seem to list `cholmod_factor_ldetA` in the last version either, so I think I am misunderstanding something here. ).

| Remote Machine/R | result |
| --- | --- |
{os: macos-latest,   r: 'release'} | Passes R-CMD check |
{os: windows-latest, r: 'release'} | Error: `function 'cholmod_factor_ldetA' not provided by package 'Matrix'` |
{os: ubuntu-latest,   r: 'release'} | Error: `function 'cholmod_factor_ldetA' not provided by package 'Matrix'` |
{os: ubuntu-latest,   r: 'oldrel-1'} | Passes R-CMD check|

The offending line is calling a function that uses `lme4::lmer` and `lme4::VarCorr`.

R-CMD check passes locally where `sessionInfo` is:

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS
...
lme4_1.1-34  
MatrixModels_0.5-2 
```

I know I'm a little out of date locally, but I'm surprised to have different results on different machines with the github actions.
Any advice would be appreciated and thanks for the great package!

**Comment by bbolker** [comment]
As commented here and elsewhere, this all has to do with a recent coordinated update of Matrix/RcppEigen/lme4, and the problem appears to be that things are still out of sync on RSPM (or some other upstream repo?) If you can force install of all three from up to date CRAN tarballs that should work otherwise you probably just have to wait...

**Comment by bbolker** [comment]
See https://github.com/lme4/lme4/issues/758; that poster's issue was resolved by `install.packages("Matrix")`

**Comment by JoeAM11** [comment]
Hello Bbolker the suggestion indeed solves the problem ! 

Thanks for the quick followup. 
Regards.

**Comment by Ulthran** [comment]
For me, including `Matrix (>=1.6-2)` in the description fixed the issue of some CI runs failing.
