### ISSUE TITLE
lmer function call a fonction that doesn't exist in the matrix package

### ISSUE THREAD

**Issue by PierreSolomon** [lme4/lme4#765]
Hello,

I'm using the lmer function to generate residual according to the [longmixr package vignette](https://cellmapslab.github.io/longmixr/articles/analysis_workflow.html#effect-of-confounders).
My code worked again last year but when I tried to relanch it today, I got an error saying that a function doesn't exist in the Matrix package:

```
> lmer(COGNITION ~ age + (1 \| ID), data = cluster_data)
Erreur dans initializePtr() :    la fonction 'chm_factor_ldetL2' n'existe pas dans le package 'Matrix'
```

**Comment by bbolker** [comment]
This has been asked and answered a few times: [this](https://stackoverflow.com/a/77532685/190277) is probably the canonical answer. **tl;dr** re-install `lme4` from source if possible, otherwise update/install the package from a binary repository that has  a sufficiently newly built version of `lme4`.
