### ISSUE TITLE
Individual sample as random effect with lmer

### ISSUE THREAD

**Issue by LukeLikesDirt** [lme4/lme4#767]
I am fitting binomial, Poisson, and Gaussian models on the same samples using lme4 to test differences between two groups. Each group has three sites and 10 samples per site. I find that nesting each sample in site as random effects (1 | sample/site) improves model fit on the binomial and Poisson models based on AIC and improves predictions based on RMSE. Hoewvevr, I cannot nest sample in site for my continuous data because the 'lmer' function does not allow as many random effects as sites.

After consideration, I think this is why, but I can't find any literature to support my case.

I cannot use sample as a random effect in model fitting on a Gaussian error distribution because data points are typically assumed to be measurements from a continuous distribution. In contrast, models fitting with count or presence-absence data (Poisson and binomial error distributions) each sample represents a discrete observation or event, and each unit (here sample) can be considered an individual test case.

Why won't the 'lmer' function allow individual samples to be set as a random effect?

Cheers
Luke

**Comment by bbolker** [comment]
Because in a model with a Gaussian error term (i.e., a linear rather than a *generalized* linear mixed models), a Gaussian observation-level random effect would be confounded with the residual error term. In the case of other response distributions with non-fixed scale parameters (Gamma, negative binomial, etc.), there is strong but incomplete confounding (we are including 'dispersion' in the model in two different ways). That is, the presence of an explicit dispersion term in the model is more relevant than continuous vs. discrete.

`lme4` will let you override this error if you really want (see `check.nobs.vs.nlev` in `?lmerControl`). Other packages (`nlme`, `glmmTMB` will let you set the residual variance to zero (or nearly zero), `lmer` can't allow this for technical reasons.

If you want a literature reference for this you can quote:

Bolker, Benjamin M. “Generalized Linear Mixed Models.” Chapter 13 in *Ecological Statistics: Contemporary Theory and Application*, edited by Gordon A. Fox, Simoneta Negrete-Yankelevich, and Vinicio J. Sosa. Oxford University Press, 2015.

> Linear mixed models assume the observations to be normally distributed conditional on the fixed-effect parameters and the conditional modes. Thus, they need to estimate the residual variance at the level of observations. If there is only one observation for each level of a grouping variable, the variance of the corresponding random effect will be confounded with the residual variance—we say that the variance of the observation-level random effect is *unidentifiable*. For example, if we decided to treat year as categorical variable in the tundra ecosystem analysis, and included a random effect of the site × year interaction, we would have exactly one observation for each site-by-year combination, and this random effect variance would be confounded with the residual variance. Many packages (e.g., nlme) will fail to detect this problem, and will give arbitrary answers for the residual variance and the confounded random-effect variance. The same situation applies for any GLMM where the scale parameter determining the variance is estimated rather than fixed, such as Gamma GLMMs or quasi-likelihood models.

**Comment by LukeLikesDirt** [comment]
Hi bbolker 

Thank you for your clear and considerate reply, and for providing that reference. It was very helpful to me.

I’ve encountered this issue multiple times across various datasets. I’ve noticed that I can use nlme and glmmTMB to overcome the issue and fit a linear model with sample as a random effect. However, in every case so far, when my generalized models are best fitted with sample as a random effect, having sample as a random effect in the linear models on the same data does not improve model fit. As a result, I’ve stopped trying to include it in linear models and keep my workflow in lme4. Nevertheless, I remained curious about the underlying reasons for this discrepancy.

Thanks again for your insights!

Cheers
Luke
