### ISSUE TITLE
update a lmer model does not use the last parameters

### ISSUE THREAD

**Issue by covaruber** [lme4/lme4#788]
Dear Ben and collaborators, I was wondering if there is any way to use update() of a lmer model only for one evaluation (iteration) and use the same variance components from the last model. For example, the following model:

```
library(lme4)
fm1 <- lmer(Reaction ~ Days + (Days || Subject), sleepstudy)
vc <- VarCorr(fm1); print(vc,comp=c("Variance"))
# Groups    Name        Variance
# Subject   (Intercept) 627.569 
# Subject.1 Days         35.858 
# Residual              653.584 
```
I am able to run it for fewer iterations using the maxeval argument inside the lmerControl (although not sure that it behaves as expected since any value between 1 to 10 evaluations seems to give the same result):

```
fm2 <- lmer(Reaction ~ Days + (Days || Subject), sleepstudy,
            control=lmerControl(
              calc.derivs=FALSE,
              optCtrl=list(maxeval=5)
            )
)
vc <- VarCorr(fm2); print(vc,comp=c("Variance"))
# Groups    Name        Variance
# Subject   (Intercept) 645.102 
# Subject.1 Days         40.319 
# Residual              645.102 
```

but when trying to update for one iteration it starts from scratch instead of using the previous values:

```
fm3 <- update(fm2, 
              control=lmerControl(
                calc.derivs=FALSE,
                use.last.params = TRUE,
                optCtrl=list(maxeval=1)
              )
)
vc <- VarCorr(fm3); print(vc,comp=c("Variance"))
# Groups    Name        Variance
# Subject   (Intercept) 593.35  
# Subject.1 Days        593.35  
# Residual              593.35 
```

Any idea how to ensure that the updated model starts from the parameter values where it stoped? I tried using the " use.last.params" argument as you can see but it didn't do the trick. Any advice? I don't want to use refit() because in my particular problem I want to provide a bigger dataset to the update(). Thanks in advance. 

Cheers

**Comment by bbolker** [comment]
Here are some answers; I think a little bit more context might help.

```r
library(lme4)
fm1 <- lmer(Reaction ~ Days + (Days || Subject), sleepstudy)
vc1 <- VarCorr(fm1); print(vc1,comp=c("Variance"))

##  Groups    Name        Variance
##  Subject   (Intercept) 627.569 
##  Subject.1 Days         35.858 
## Residual              653.584
```

Set up a new, expanded data frame (so we can test in a slightly realistic context):

```r
newrep <- function(data, sub_off = 1000) {
    transform(data, Subject = factor(as.numeric(as.character(Subject)) + sub_off))
}

set.seed(101)
ss_expand <- do.call(rbind,
                     lapply((1000)*(1:5),
                            newrep, data = sleepstudy))
table(ss_expand$Subject)
```

Use `update()`, but set `start` to the previous fitted `theta` values (elements of the *scaled* Cholesky factor, which in this case are the *scaled* standard deviations: this will be relevant later).

```r
fm2 <- update(fm1,
              start = getME(fm1, "theta"),
              data = ss_expand,
              control = lmerControl(optCtrl = list(maxeval= 1),
                                    calc.derivs = FALSE))
```

This looks like it hasn't worked: the variances are not quite equal to the original values.
```r
vc2 <- VarCorr(fm2); print(vc2, comp=c("Variance"))

##  Groups    Name        Variance
##  Subject   (Intercept) 621.978 
##  Subject.1 Days         35.539 
##  Residual              647.761 
```

**However**, this is a difficult-to-avoid consequence of the way that `lmer` is set up. The estimated parameters, which are the scaled SDs (i.e. `SD(RE_i)/SD(resid)`), are in fact held constant:

```r
stopifnot(all(getME(fm1, "theta") == getME(fm2, "theta")))  ## these are identical/code doesn't stop
```

The problem is that the residual variance (SD) is not an optimized parameter, but is instead calculated from the residual sum of squares.

If you can give a little bit more context to your use case, we might be able to come up with something. (I can think of a solution, which is quite ugly, where we take the modularly constructed deviance function (see below) and use it to adjust the model until the *unscaled* variances are as close as possible to those from the original fit. Ugly, but I think it would work ...

----
Here's another way to construct the same output as `fm2` (I worked this up when I was still confused about `fm2`)

```r
## modular framework: see ?lme4::modular
th <- getME(fm1, "theta")
lmod <- lFormula(Reaction ~ Days + (Days || Subject), data = ss_expand,
               start = th)
devfun <- do.call(mkLmerDevfun, L1)
opt <- list(par = th, fval = devfun(th), feval = 1, conv = 0)
fm3 <- mkMerMod(environment(devfun), opt, lmod$reTrms, fr = lmod$fr)

vc3 <- VarCorr(fm3); print(vc3, comp=c("Variance"))

##  Groups    Name        Variance
##  Subject   (Intercept) 621.978 
##  Subject.1 Days         35.539 
##  Residual              647.761 
```

**Comment by covaruber** [comment]
The two answers are helpful Ben. I think both are equally good for our problem. I guess I didn't understand how to use the argument "start".  The context was that in our particular case we want to expand the dataset but provide some good initial values for the variance components with a smaller dataset and potentially force the variance components. Thanks a lot for your valuable insight along these years to all the community Ben.

Cheers,
Eduardo
