### ISSUE TITLE
Compilation failure for `lme4` 1.1-35.4 using `R < 4.4`

### ISSUE THREAD

**Issue by ebete** [lme4/lme4#797]
`lme4 1.1-35.4` requests `Matrix (>=1.6.2)` (shouldn't this be `1.6-2`, dash instead dot? Not sure if that matters) for compilation, but has a requirement of 1.2-1.

This results in a failure to build/install `lme4`, and any package depending on it.

See: 67dc869257f6717ed6bd6501ac35c81d536af269

## Environment

- `R version 4.3.1 (2023-06-16)`
- `platform x86_64-pc-linux-gnu`

## Installation log

```
* installing *source* package ‘lme4’ ...
** package ‘lme4’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
Error: package ‘Matrix’ 1.6-1 was found, but >= 1.6.2 is required by ‘lme4’
* removing ‘/usr/local/lib/R/site-library/lme4’
```

**Comment by bbolker** [comment]
You're right that it should be 1.6-2 and not 1-6.2, but also that it doesn't matter:

```r
as.package_version("1-6.2") == as.package_version("1.6-2")  ## TRUE
```

However, the main point is that Matrix version 1.6-2 only *depends* on R >= 3.5.0.  I did run into problems installing the latest version of `lme4`, but that has to do with the configuration of the repositories rather than the requirements of the packages themselves. However, the installation process below is fairly complex - I don't know if there are ways to simplify it for users (for example, if the `nloptr` package can be installed from a binary package - that would remove the need to have `cmake` installed ...)

```
docker pull rocker/r-ver:4.3.1
docker run --rm -ti rocker/r-ver:4.3.1 bash
apt update && apt upgrade -y && apt install -y cmake  ## needed for nloptr
R
```

From R:

```
options(repos = c(CRAN="http://cran.r-project.org"))
install.packages("remotes")
remotes::install_version("Matrix", "1.6.2")
install.packages("lme4")
library(lme4)
example(lmer)
```

For the record, this dependency was added to allow for the changes made [here](https://github.com/lme4/lme4/pull/746), to solve [this](https://github.com/lme4/lme4/issues/745) ...

**Comment by jaganmn** [comment]
The dependency seems spurious: https://github.com/lme4/lme4/pull/793#issuecomment-2183427685

**Comment by bbolker** [comment]
Cross-ref to https://github.com/lme4/lme4/pull/793

**Comment by bbolker** [comment]
Dependence on 1.6-2 is definitely spurious and should be backed out. Tested at least back to 1.5-1. Ideally should test to see if Matrix 1.2-1 is actually OK ...

**Comment by bbolker** [comment]
I still don't understand exactly why this error happened in the first place (it should be possible to install `Matrix` 1.6.2 on R < 4.4), but the most recent update on CRAN sets the `Matrix` requirement back to 1.2-3 (IIRC).
