### ISSUE TITLE
tests\README.md confusion

### ISSUE THREAD

**Issue by RossBoylan** [lme4/lme4#802]
First, the file says
* `testthat` testing: tests in `inst/tests` can be run in the framework of the `testthat` package, specifically via `tests/test-all.R`

There is no such file `tests/test-all.R`.

Second, aside from that, it is unclear why there are 2 sets of tests, which circumstances they are run in, and how to decide where to put new tests.  The files directly under `tests` are mostly without an `.Rout.save` file, which is the documented way to use them.  Further, some of them (e.g., `tests\simulate.R`) use `testthat`, which makes me wonder why they aren't in the `tests\testthat` directory.  All the files under `tests\testthat` that I've checked explicitly load `testthat` and `lme4`, which I do not believe is the recommended style for `testthat`.

Speculation
=======
The files directly under `tests` are run as part of the standard `R CMD check` process (well, at least the ones with appropriate `LME4_TEST_LEVEL`).  These mostly rely on `stopifnot()` to indicate test failure; for those with an `.Rout.save` file, disagreement with that file will also trigger a report (but not a failure).

The files under `tests\testthat` are only run manually (the `R` [documentation](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-subdirectories) is unclear on this point).  Unclear if there is an easy way to run them all.

**Comment by bbolker** [comment]
`tests/test-all.R` was moved to [tests/AAAtest-all.R](https://github.com/lme4/lme4/blob/master/tests/AAAtest-all.R) so that those tests are run first. (This file essentially just runs   `testthat::test_check("lme4")`, which runs all the tests in `tests/testthat`.)

I don't remember clearly, but I suspect that the reason we mostly don't use the `.Rout.save` comparison mechanism is

* it's not useful for testing approximate equality up to a desired tolerance (as in `all.equal()`)
* because mismatches *don't* produce warnings but *do* trigger complaints from CRAN, problems aren't flagged as obviously

The "classic" (`tests/*.R`/`stopifnot`/`.Rout` check) are older; new tests are always (?) added to the `testthat/tests` collection. I would love to port the entire collection to [tinytest](https://cran.r-project.org/web/packages/tinytest/index.html) at some point.

Is there a particular reason you're interested in the testing framework?

**Comment by RossBoylan** [comment]
I'm interested in the tests because I'm adding a hook to give more control over the random numbers generated for clusters, following up on your suggestion about a week ago.  I think there's a relatively clean way to do it and have written the code for it.  I wanted to add a test to make the possible contribution complete--as well as seeing if it actually worked :)

The hook would actually cater to a number of cases, and so there might be a justification for the added complexity.

So it sounds as if adding a test in testthat would be preferred, except I think the existing simulation tests are directly under tests/ and so it might be expedient to add my test there.

Ross

________________________________________

**Comment by bbolker** [comment]
FWIW there are also simulation tests in `test-predict.R` ...
