### ISSUE TITLE
Calling summary() on a model with a fixed effect causes segmentation fault

### ISSUE THREAD

**Issue by celprov** [lme4/lme4#805]
Here is a simple script I was trying to run 

```
library(lme4)

df <- read.csv(file = '../../data/IXI_augmented_ratings_df.tsv', sep='\t')
fm1 <- lmer(as.numeric(rating) ~ defaced + (1 | subject) + (1 | rater_id) , data=df, REML=FALSE)
summary(fm1) 
```
Running this script results in the segmentation fault error below.
```
 *** caught segfault ***
address 0x1, cause 'memory not mapped'

Traceback:
 1: .Call(dpoMatrix_trf, A, if (perm) 1L else 2L, perm, tol)
 2: .local(A, ...)
 3: Cholesky(from, perm = FALSE)
 4: Cholesky(from, perm = FALSE)
 5: doTryCatch(return(expr), name, parentenv, handler)
 6: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 7: tryCatchList(expr, classes, parentenv, handlers)
 8: tryCatch(Cholesky(from, perm = FALSE), error = function(e) NULL)
 9: .dsy2dpo(.M2sym(from))
10: asMethod(object)
11: as(V, "dpoMatrix")
12: doTryCatch(return(expr), name, parentenv, handler)
13: tryCatchOne(expr, names, parentenv, handlers[[1L]])
14: tryCatchList(expr, classes, parentenv, handlers)
15: tryCatch(as(V, "dpoMatrix"), error = function(e) e)
16: vcov.merMod(object, use.hessian = use.hessian)
17: vcov(object, use.hessian = use.hessian)
18: summary.merMod(fm1)
19: summary(fm1)
20: summary(fm1)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault (core dumped)
```
However, if I remove the line summary(fm1), the code runs successfully until the end. 
- The problem does not occur when only random effects are added in the formula (e.g  (1 | subject) + (1 | rater_id)  +  ( 1| defaced)). I have tried countless random effects, so the error is raised by fixed effects specifically.
- The problem replicates when adding another variable as fixed effect, so this issue is not linked with the defaced variable specifically. 
- I run into the same error when running the same model on simulated data with the same structure. 
- The problem replicated when running the code via Rscript but also inside a jupyter notebook with a R kernel.

I have R version 
```
R version 4.4.0 (2024-04-24) -- "Puppy Cup"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu
```
and lme4 version 1.1.35.3

**Comment by bbolker** [comment]
This is almost certainly due to a mismatch in the binary versions of `lme4`/`Matrix` , as described in [this Stack Overflow post](https://stackoverflow.com/questions/77481539/error-in-initializeptr-function-cholmod-factor-ldeta-not-provided-by-pack). Try

```r
oo <- options(repos = "https://cran.r-project.org/")
utils::install.packages("Matrix")
utils::install.packages("lme4")
options(oo)
```
(from a clean R session) and see if that resolves the problem.

**Comment by celprov** [comment]
Hi @bbolker, thank you for your fast answer.
What do you mean by a clean R session?
I tried running `R` in the terminal, and performed the aforementioned step in the terminal session, but this did not solve the issue.

**Comment by bbolker** [comment]
A 'clean' R session means an R session with no packages other than the base packages loaded (if you're not restoring saved workspaces or using an `Rprofile` file, this should happen when you restart R) &mdash; shouldn't matter if it's RStudio or Jupyter notebook or terminal, although the terminal provides the least scope for other weird things to happen.

This could be hard to debug. I still think it's  a package binary incompatibility problem, as it's hard to imagine any other explanation &mdash; this is a very standard model, here's a similar (meaningless but) simple example that works for me and presumably fails for you [please try it]:

```r
library(lme4)
## mtcars data set comes with base R
fm1 <- lmer(mpg ~ disp + (1|cyl) + (1|carb), data = mtcars, REML = FALSE)
summary(fm1)
```

Some guesses/requests for further info:

* can you post the results of `sessionInfo()` and the full session in which you try to install the packages? (i.e. do you get any warnings or errors suggesting that the install process has failed?) [please post as text in a code block rather than as a screenshot image]
* perhaps you have multiple libraries, i.e. copies of the package(s) in more than one place? What do you get from

```r
pkgvers <- function(lib) { sapply(c("Matrix", "lme4"), function(p) try(packageVersion(p, lib.loc = lib), silent = TRUE)) }
lapply(.libPaths(), pkgvers)
```

(the existence/version of a package won't immediately tell us about binary compatibility but could provide a hint)

**Comment by bbolker** [comment]
Any more news on this?

**Comment by bbolker** [comment]
Closing. Will re-open if we get more information.

**Comment by celprov** [comment]
I recently installed R on another computer, and now I have no problem calling summary(fm1). It seems indeed that there were version incompatibilities.
