### ISSUE TITLE
refactor mkLmerDevFun, mkGlmerDevFun and mkdevfun

### ISSUE THREAD

**Issue by dmbates** [lme4/lme4#92]
`mkdevfun` has some messy logic to determine if it is being called with an `lmerResp` or `glmerResp` object.  It would be easier to incorporate the small piece of code from `mkdevfun` that is actually called for an lmer model back into `mkLmerDevFun`.

**Comment by mmaechler** [comment]
Now (even considering #308), 
- I see that we also have  `as.function.merMod()` method calling `mkdevfun()` [will pass the `...`, or add the optional args from mkdevfun() there] 
- *and* there is a _third_ exported function, `updateGlmerDevfun()`, also returning a `mkdevfun()` result.    So we have 4 exported i.e., user-available functions returning the result of mkdevfun().
- the first argument of `mkdevfun()`, namely the environment  `rho` is not easy to construct for the user. So (s)he really should rather use one of the other 4 ways to get that.  I now propose to follow @dmbates idea (as I understand it), and then *remove* the mkdevfun() help page, also closing #308

**Comment by bbolker** [comment]
Quick comment:  I'd need to look at this to remember all the details.  I assume that if this passes our tests we haven't broken anything, although I'd be a little bit cautious because modular uses of these functions might not be well-covered by tests (I could re-run the downstream-packages tests this weekend ...)

I vaguely recall that there was an issue with extracting deviance functions from glmerMod objects - i.e. at one point we could get devfuns from lmerMods by extracting the right pieces, whereas we had to re-evaluate the call for glmerMods ... ?

**Comment by mmaechler** [comment]
There is no change to the inner structures, so "extracting" the functions from `lmerMod` or `glmerMod` should not have changed.  Also `mkdevfun` is not changed ... rather IU @dmbates that mkLmerDevFun() should directly do what it needs instead of going a "slowish" detour via `mkdevfun()`.
The 2nd proposal is more related to #308: Namely to decide *not* to export it, and hence remove its help page.

**Comment by bbolker** [comment]
OK, thanks.
